ALTER TABLE "procedure_version" ADD COLUMN "period" jsonb;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "scope" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "source_snapshot" jsonb;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "inclusion_rule" jsonb DEFAULT '{"schemaVersion":1,"all":[]}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "zero_record_pass" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "allow_versioned_duplicates" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "population_blockers" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
-- Preserve the typed meaning of Story 2.1 Templates, without selecting a source.
UPDATE "procedure_version" SET "inclusion_rule" = CASE "template_id"
  WHEN 'P-1' THEN '{"schemaVersion":1,"all":[{"column":"employment_status","kind":"text","operator":"eq","value":"Terminated"},{"column":"termination_effective_date","kind":"within-period"}]}'::jsonb
  WHEN 'P-2' THEN '{"schemaVersion":1,"all":[{"column":"status","kind":"text","operator":"eq","value":"Active"}]}'::jsonb
  WHEN 'P-3' THEN '{"schemaVersion":1,"all":[{"column":"currency","kind":"text","operator":"eq","value":"USD"},{"column":"amount","kind":"decimal","operator":"gte","value":"100000"},{"column":"processed_time","kind":"within-period"}]}'::jsonb
  ELSE '{"schemaVersion":1,"all":[]}'::jsonb END;--> statement-breakpoint
INSERT INTO "schema_meta" ("version") VALUES (8);--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_period_shape" CHECK ("procedure_version"."period" IS NULL OR coalesce(jsonb_typeof("procedure_version"."period") = 'object' AND "procedure_version"."period" - 'from' - 'to' = '{}'::jsonb AND "procedure_version"."period"->>'from' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND "procedure_version"."period"->>'to' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' AND ("procedure_version"."period"->>'from')::date <= ("procedure_version"."period"->>'to')::date AND ("procedure_version"."period"->>'from')::date >= date '0001-01-01', false));--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_scope_bound" CHECK (length("procedure_version"."scope") <= 10000);--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_source_shape" CHECK ("procedure_version"."source_snapshot" IS NULL OR coalesce(jsonb_typeof("procedure_version"."source_snapshot") = 'object' AND "procedure_version"."source_snapshot" - 'bindingId' - 'displayName' - 'digest' - 'contract' = '{}'::jsonb AND "procedure_version"."source_snapshot"->>'bindingId' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' AND "procedure_version"."source_snapshot"->>'digest' ~ '^[0-9a-f]{64}$' AND length("procedure_version"."source_snapshot"->>'displayName') BETWEEN 1 AND 200 AND jsonb_typeof("procedure_version"."source_snapshot"->'contract') = 'object' AND "procedure_version"."source_snapshot"->'contract' ?& ARRAY['kind','location','declared_schema','declared_count_mechanism','sensitive_fields'] AND ("procedure_version"."source_snapshot"->'contract') - 'kind' - 'location' - 'declared_schema' - 'declared_count_mechanism' - 'sensitive_fields' = '{}'::jsonb AND "procedure_version"."source_snapshot"->'contract'->>'kind' IN ('manual-upload','versioned-file','read-only-api') AND "procedure_version"."source_snapshot"->'contract'->>'declared_count_mechanism' IN ('cover-sheet','count-endpoint','none') AND jsonb_typeof("procedure_version"."source_snapshot"->'contract'->'declared_schema') = 'array' AND jsonb_typeof("procedure_version"."source_snapshot"->'contract'->'sensitive_fields') = 'array', false));--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_rule_shape" CHECK (coalesce(jsonb_typeof("procedure_version"."inclusion_rule") = 'object' AND "procedure_version"."inclusion_rule" - 'schemaVersion' - 'all' = '{}'::jsonb AND "procedure_version"."inclusion_rule"->'schemaVersion' = '1'::jsonb AND jsonb_typeof("procedure_version"."inclusion_rule"->'all') = 'array' AND jsonb_array_length("procedure_version"."inclusion_rule"->'all') <= 32, false));--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_count_blocker" CHECK ("procedure_version"."population_blockers" = CASE WHEN "procedure_version"."source_snapshot"->'contract'->>'declared_count_mechanism' = 'none' THEN '["declared-count-missing"]'::jsonb ELSE '[]'::jsonb END);
