ALTER TABLE "procedure_version" ADD COLUMN "compliance_schema_version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "compliance_compiler_version" text DEFAULT '1' NOT NULL;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "compliance_conditions" jsonb;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD COLUMN "agent_judged_threshold" text DEFAULT '0.80' NOT NULL;--> statement-breakpoint
-- Existing versions receive the same deterministic Template defaults as a newly created
-- Draft. This changes only the promoted Compliance Rule fields; prior section edits stay.
UPDATE "procedure_version"
SET "compliance_conditions" = CASE "template_id"
  WHEN 'P-1' THEN $json$[{"conditionId":"C1","text":"Compliant when `found = false` (proven absence) or `account_status = disabled`\nException when `account_status = active`\nany other status → Unevaluated (unnamed value)","applicability":"all records","comparison":null,"applicabilityAst":{"kind":"constant","value":true},"rule":{"kind":"predicate","predicate":{"kind":"any","expressions":[{"kind":"boolean","field":"found","value":false},{"kind":"named-set","field":"account_status","compliant":["disabled"],"exception":["active"]}]}},"status":"RULE"},{"conditionId":"C2","text":"Treat any account whose roles look privileged as an Exception even if disabled.\nA found account with no C2 evaluation is a Gate failure.","applicability":"found = true","comparison":null,"applicabilityAst":{"kind":"boolean","field":"found","value":true},"rule":null,"status":"AGENT_JUDGED"}]$json$::jsonb
  WHEN 'P-2' THEN $json$[{"conditionId":"C1","text":"No prohibited pair exists for the account.\nAt least one prohibited pair exists; report every pair.\nUnknown role, incomplete role expansion, duplicate conflicting policy entries, or incomplete account population.\nRole name to the versioned RoleMatrix; expand roles to permissions before comparison.\n`CREATE_VENDOR` + `APPROVE_VENDOR`; `CREATE_PAYMENT` + `RELEASE_PAYMENT`; `CONFIGURE_LIMITS` + `APPROVE_LOAN`","applicability":"found = true","comparison":null,"applicabilityAst":{"kind":"boolean","field":"found","value":true},"rule":{"kind":"permission-pairs","rolesField":"roles","prohibitedPairs":[["CREATE_VENDOR","APPROVE_VENDOR"],["CREATE_PAYMENT","RELEASE_PAYMENT"],["CONFIGURE_LIMITS","APPROVE_LOAN"]]},"status":"RULE"}]$json$::jsonb
  WHEN 'P-3' THEN $json$[{"conditionId":"C1","text":"A matching `APPROVED` decision exists before processing and the approver's limit is at least the transaction amount.\nNo approval, approval after processing, rejected approval, or insufficient approver limit.\nDuplicate or contradictory approval decisions, missing transaction time, missing approval limit, or incomplete population.\nExact transaction ID, with approval ID used as corroboration.\nUSD 100,000 requires approval (inclusive); this is the PoC's exercised tolerance boundary (FR-9).","applicability":"all records","comparison":{"boundary":"inclusive","threshold":"100000","tolerance":"0"},"applicabilityAst":{"kind":"constant","value":true},"rule":{"kind":"approval","amountField":"amount","currencyField":"currency","decisionField":"decision","decisionTimeField":"decided_at","processedTimeField":"processed_time","limitField":"approver_limit","threshold":"100000","boundary":"inclusive","tolerance":"0"},"status":"RULE"}]$json$::jsonb
  WHEN 'P-4' THEN $json$[{"conditionId":"C1","text":"Observed and approved normalized values are equal.\nValue differs or an extra production parameter is explicitly prohibited by the baseline.\nRequired parameter absent from the observation, multiple effective baselines apply, observation is stale, or extraction is partial.\nExact parameter name.\n`max_manual_approval_amount`, `mfa_required_for_admin`, `session_timeout_minutes`, and `production_debug_mode`","applicability":"all records","comparison":null,"applicabilityAst":{"kind":"constant","value":true},"rule":{"kind":"baseline","parameterField":"parameter","observedField":"observed_value","observationTimeField":"observation_time","tolerance":"0"},"status":"RULE"}]$json$::jsonb
END;--> statement-breakpoint
ALTER TABLE "procedure_version" ALTER COLUMN "compliance_conditions" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_compliance_schema" CHECK ("procedure_version"."compliance_schema_version" = 1);--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_compliance_compiler" CHECK ("procedure_version"."compliance_compiler_version" = '1');--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_compliance_shape" CHECK (coalesce(jsonb_typeof("procedure_version"."compliance_conditions") = 'array' AND jsonb_array_length("procedure_version"."compliance_conditions") BETWEEN 1 AND 32, false));--> statement-breakpoint
ALTER TABLE "procedure_version" ADD CONSTRAINT "procedure_version_confidence_range" CHECK (CASE WHEN length("procedure_version"."agent_judged_threshold") <= 100 AND "procedure_version"."agent_judged_threshold" ~ '^-?(0|[1-9][0-9]*)([.][0-9]+)?$' THEN "procedure_version"."agent_judged_threshold"::numeric BETWEEN 0 AND 1 ELSE false END);
--> statement-breakpoint
-- `drizzle-kit generate` does not write this line. The compatibility range is generation
-- 10 in the same change; only release/CI runs the migrator (AD-15).
INSERT INTO "schema_meta" ("version") VALUES (10);
