import type { ReactNode } from 'react';
import { useCallback, useEffect, useId, useRef, useState } from 'react';
import { AccessError } from './auth';
import type { Session } from './auth';
import { applySkillCatalog, discardSkillActions, discardSkillPending, freezeSkillAction, prepareSkillInstall, readSkillCatalog, recoverSkillAction, recoverSkillDraft, retainSkillAction, retainSkillDraft, skillAudience, skillFailure, skillRefused, skillTools, skillCustodyFailure, skillProseError, validateSkillInstall, readSkillAssignments, readSkillStatusHistory } from './skills';
import type { CatalogAction, InstallSkill, SkillCatalogReceipt, SkillVersion, SkillStatusDraft, SkillFieldErrors, SkillAssignmentPage, SkillStatusHistory } from './skills';
import { SkillDetails } from './SkillDetails';
import { useSkillInspection } from './useSkillInspection';

interface Props { organisation: string; session: Session; accessReady: boolean; onAccessFailure: (error?: AccessError) => void }
const blank = (revision: string): InstallSkill => ({ key: crypto.randomUUID(), expected_revision: revision, assignment: { kind: 'firm', client_id: null, engagement_id: null }, applicability: { audit_area: null, period_start: null, period_end: null }, enabled: false,
  manifest: { schema_version: 1, id: '', version: 'v1', name: '', description: '', source: { reference: '', revision: '', license: '' }, inputs: [], outputs: [], needs: [], method_version_ids: [], resources: [] } });
const lines = (value: string) => value ? value.split('\n') : [];
const ids = (value: string) => lines(value);

export function SkillCatalog({ organisation, session, accessReady, onAccessFailure }: Props) {
  const owner = skillAudience(session, organisation);
  const [draft, updateDraft] = useState<InstallSkill | null>(() => { const saved = recoverSkillDraft(owner, session); return saved?.kind === 'install-draft' ? saved.body : null; });
  const [statusDraft, updateStatusDraft] = useState<SkillStatusDraft | null>(() => { const saved = recoverSkillDraft(owner, session); return saved?.kind === 'status-draft' ? saved.body : null; });
  const [fields, setFields] = useState<SkillFieldErrors>({});
  const formId = useId();
  function keepDraft(value: InstallSkill | SkillStatusDraft | null, status = false) {
    const saved = retainSkillDraft(owner, session, value ? status ? { kind: 'status-draft', organisation_id: organisation, body: value as SkillStatusDraft } : { kind: 'install-draft', organisation_id: organisation, body: value as InstallSkill } : null); if (!saved) setError(skillCustodyFailure); return saved;
  }
  function setDraft(value: InstallSkill | null) { if ((value || !statusDraft) && !keepDraft(value)) return; updateDraft(value); }
  function setStatusDraft(value: SkillStatusDraft | null) { if ((value || !draft) && !keepDraft(value, true)) return false; updateStatusDraft(value); return true; }
  const describe = (field: string) => ({ 'aria-invalid': !!fields[field], 'aria-describedby': fields[field] ? `${formId}-${field}` : undefined });
  const fieldError = (field: string) => fields[field] ? <p id={`${formId}-${field}`} className="notice">{fields[field]}</p> : null;

  const [pending, setPending] = useState<CatalogAction | null>(() => { const value = recoverSkillAction(owner, session); return value && value.kind !== 'select' ? value : null; });
  const [receipt, setReceipt] = useState<SkillCatalogReceipt | null>(null);
  const [error, setError] = useState('');
  const [working, setWorking] = useState(false);
  const action = useRef<AbortController | null>(null);
  const latest = useRef({ owner, accessReady }); latest.current = { owner, accessReady };
  const mounted = useRef(true);
  const withdrawPrivate = useCallback((reason?: AccessError) => { discardSkillActions(owner); updateDraft(null); updateStatusDraft(null); setPending(null); setReceipt(null); onAccessFailure(reason); }, [owner, onAccessFailure]);
  const read = useCallback((signal: AbortSignal) => readSkillCatalog(organisation, session, signal), [organisation, session.identity.id, session.csrf_token]);
  const inspection = useSkillInspection(owner, accessReady, '', read, withdrawPrivate);
  const snapshot = inspection.value;
  const visible = inspection.verified;
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; action.current?.abort(); }; }, []);
  function change(update: (value: InstallSkill) => void) { if (!draft || pending) return; const value = structuredClone(draft); update(value); setDraft(value); if (Object.keys(fields).length) setFields(validateSkillInstall(value)); }
  function edit(version?: SkillVersion) { if (!snapshot) return; const value = version ? structuredClone(version.command) : blank(snapshot.revision); value.key = crypto.randomUUID(); value.expected_revision = snapshot.revision; if (version) { value.manifest.version = ''; value.enabled = false; } if (!keepDraft(value)) return; updateDraft(value); updateStatusDraft(null); setFields({}); setReceipt(null); setError(''); }
  function changeStatus(version: SkillVersion, status: SkillStatusDraft['status']) { if (!snapshot || !setStatusDraft({ version, status, reason: '', expected_revision: snapshot.revision })) return; updateDraft(null); setFields({}); setError(''); }
  async function apply(command: CatalogAction) {
    if (!visible || action.current) return;
    if (!retainSkillAction(owner, session, command)) { setError(skillCustodyFailure); return; }
    const expectedOwner = owner, recovering = pending !== null, controller = new AbortController(); action.current = controller;
    inspection.cancel(); setPending(command); setWorking(true); setError(''); setReceipt(null);
    const deadline = setTimeout(() => controller.abort(), 8000);
    try {
      const confirmed = await applySkillCatalog(command, session, controller.signal);
      if (!mounted.current || latest.current.owner !== expectedOwner) return;
      discardSkillActions(owner); setPending(null); updateDraft(null); updateStatusDraft(null); setReceipt(confirmed);
    } catch (reason) {
      if (!mounted.current || latest.current.owner !== expectedOwner) return;
      if (skillRefused(reason, recovering)) { discardSkillPending(owner); setPending(null); }
      setError(skillFailure(reason, recovering));
      if (reason instanceof AccessError && [401, 403, 404, 412].includes(reason.status)) withdrawPrivate(reason);
    } finally { clearTimeout(deadline); if (action.current === controller) { action.current = null; if (mounted.current) { setWorking(false); void inspection.refresh(); } } }
  }
  function save() { if (!draft) return; const errors = validateSkillInstall(draft); setFields(errors); if (Object.keys(errors).length) { setError('Review the highlighted skill fields. Your exact draft is retained.'); return; } try { void apply(freezeSkillAction({ kind: 'install', organisation_id: organisation, body: prepareSkillInstall(draft) })); } catch { setError('Check the highlighted skill fields and current catalog basis before submitting.'); } }
  function saveStatus() { if (!statusDraft) return; const reason = skillProseError(statusDraft.reason); setFields(reason ? { status_reason: reason } : {}); if (reason) { setError('Review the highlighted status reason. Your exact draft is retained.'); return; } void apply(freezeSkillAction({ kind: 'status', organisation_id: organisation, body: { key: crypto.randomUUID(), expected_revision: statusDraft.expected_revision, version_id: statusDraft.version.id, status: statusDraft.status, reason: statusDraft.reason } })); }
  return <section ref={inspection.panel} className="skill-catalog" aria-label="Installed skills"><div className="methodology-heading"><div><h2>Installed skills</h2><p>Install attributable techniques for your firm. Installation grants no client access or additional Permissions.</p></div><button type="button" disabled={!visible || working || !!pending} onClick={() => edit()}>Install skill</button></div>
    {!visible ? <p role="status">{inspection.error || 'Checking current skill access…'}</p> : null}
    <button type="button" className="text-button" disabled={!accessReady || inspection.loading || working} onClick={() => void inspection.refresh()}>Refresh skill catalog</button>
    <div hidden={!visible}>
      {error ? <p className="notice" role="alert">{error}</p> : null}
      {receipt ? <section className="notice" role="status"><strong>Skill catalog change recorded.</strong><p>Version {receipt.version_id} · {receipt.status} · revision {receipt.revision} · attributed to {receipt.actor_id}.</p><p>{receipt.affected_selections} affected selections retain their original history; current eligibility is checked separately.</p></section> : null}
      {pending ? <section className="notice" aria-label="Unconfirmed skill request"><h3>{working ? 'Recording skill change…' : 'Skill delivery unconfirmed'}</h3><p>The original request and key are retained. Retry recovers the exact receipt under current access.</p><button type="button" disabled={working} onClick={() => void apply(pending)}>Retry exact skill request</button></section> : null}
      {draft && snapshot ? <form className="methodology-editor" aria-label="Install skill version" aria-describedby={fields.manifest ? `${formId}-manifest` : undefined} onSubmit={event => { event.preventDefault(); save(); }}><fieldset disabled={working || !!pending}><legend>Install immutable skill version</legend>
        <p>Names, input labels and audit area allow up to 200 Unicode characters. Purpose, provenance, outputs and reasons allow up to 2000. Text is preserved exactly.</p>
        {fieldError('manifest')}{fieldError('manifest.inputs')}{fieldError('manifest.needs')}{fieldError('manifest.resources')}
        <p>Edit installs a new version. Existing manifests, resources, selections and receipts remain exact. Enabling makes a compatible technique selectable; it does not execute it.</p>
        {draft.expected_revision !== snapshot.revision ? <section className="notice"><p>The catalog changed. Review the current versions before installing your retained draft.</p><button type="button" className="quiet-button" onClick={() => setDraft({ ...draft, key: crypto.randomUUID(), expected_revision: snapshot.revision })}>Use latest skill catalog revision</button></section> : null}
        <div className="methodology-grid"><label>Skill identifier<input required maxLength={128} pattern="(?:[A-Za-z0-9_]|-)+" {...describe('manifest.id')} value={draft.manifest.id} onChange={event => change(value => { value.manifest.id = event.target.value; })} /></label>{fieldError('manifest.id')}<label>Skill version<input required maxLength={128} pattern="(?:[A-Za-z0-9_]|-)+" {...describe('manifest.version')} value={draft.manifest.version} onChange={event => change(value => { value.manifest.version = event.target.value; })} /></label>{fieldError('manifest.version')}<label>Skill name<input required {...describe('manifest.name')} value={draft.manifest.name} onChange={event => change(value => { value.manifest.name = event.target.value; })} /></label>{fieldError('manifest.name')}</div>
        <label>Technique purpose<input required {...describe('manifest.description')} value={draft.manifest.description} onChange={event => change(value => { value.manifest.description = event.target.value; })} /></label>{fieldError('manifest.description')}
        <fieldset><legend>Package provenance</legend><label>Skill source reference<input required {...describe('manifest.source.reference')} value={draft.manifest.source.reference} onChange={event => change(value => { value.manifest.source.reference = event.target.value; })} /></label>{fieldError('manifest.source.reference')}<label>Skill source revision<input required {...describe('manifest.source.revision')} value={draft.manifest.source.revision} onChange={event => change(value => { value.manifest.source.revision = event.target.value; })} /></label>{fieldError('manifest.source.revision')}<label>Skill license<input required {...describe('manifest.source.license')} value={draft.manifest.source.license} onChange={event => change(value => { value.manifest.source.license = event.target.value; })} /></label>{fieldError('manifest.source.license')}<p>Record the exact package you chose to install. Structural validation and digests do not certify its content. Acquired evidence never installs itself.</p></fieldset>
        <fieldset><legend>Skill availability and applicability</legend><div className="methodology-grid"><label>Skill availability scope<select value={draft.assignment.kind} onChange={event => change(value => { value.assignment = { kind: event.target.value as InstallSkill['assignment']['kind'], client_id: null, engagement_id: null }; })}><option value="firm">All firm engagements</option><option value="client">One client</option><option value="engagement">One engagement</option></select></label>
          {draft.assignment.kind !== 'firm' ? <SkillAssignmentOptions organisation={organisation} session={session} accessReady={visible} assignment={draft.assignment} onAccessFailure={withdrawPrivate} onChange={assignment => change(value => { value.assignment = assignment; })} describe={describe} fieldError={fieldError} /> : null}
          <label>Skill audit area<input {...describe('applicability.audit_area')} value={draft.applicability.audit_area ?? ''} onChange={event => change(value => { value.applicability.audit_area = event.target.value || null; })} /></label>{fieldError('applicability.audit_area')}<label>Skill period start<input type="date" {...describe('applicability.period_start')} value={draft.applicability.period_start ?? ''} onChange={event => change(value => { value.applicability.period_start = event.target.value || null; })} /></label>{fieldError('applicability.period_start')}<label>Skill period end<input type="date" {...describe('applicability.period_end')} value={draft.applicability.period_end ?? ''} onChange={event => change(value => { value.applicability.period_end = event.target.value || null; })} /></label>{fieldError('applicability.period_end')}</div>
          <label>Required exact methodology versions<textarea rows={2} placeholder="One exact stored version ID per line; blank for an independent technique" {...describe('manifest.method_version_ids')} value={draft.manifest.method_version_ids.join('\n')} onChange={event => change(value => { value.manifest.method_version_ids = ids(event.target.value); })} /></label>{fieldError('manifest.method_version_ids')}<label className="methodology-check"><input type="checkbox" checked={draft.enabled} onChange={event => change(value => { value.enabled = event.target.checked; })} />Enable this version when installed</label></fieldset>
        <fieldset aria-describedby={fields['manifest.inputs'] ? `${formId}-manifest.inputs` : undefined}><legend>Declared inputs and outputs</legend><p>At most 32 inputs and 32 output descriptions; one output per line.</p>{draft.manifest.inputs.map((input, index) => <div className="methodology-requirement" key={index}><label>Input identifier<input required pattern="(?:[A-Za-z0-9_]|-)+" maxLength={128} {...describe(`manifest.inputs.${index}.id`)} value={input.id} onChange={event => change(value => { value.manifest.inputs[index]!.id = event.target.value; })} /></label>{fieldError(`manifest.inputs.${index}.id`)}<label>Input label<input required {...describe(`manifest.inputs.${index}.label`)} value={input.label} onChange={event => change(value => { value.manifest.inputs[index]!.label = event.target.value; })} /></label>{fieldError(`manifest.inputs.${index}.label`)}<label className="methodology-check"><input type="checkbox" checked={input.required} onChange={event => change(value => { value.manifest.inputs[index]!.required = event.target.checked; })} />Required input</label><button type="button" className="text-button" onClick={() => change(value => { value.manifest.inputs.splice(index, 1); })}>Remove input {index + 1}</button></div>)}<button type="button" className="quiet-button" disabled={draft.manifest.inputs.length >= 32} onClick={() => change(value => { value.manifest.inputs.push({ id: crypto.randomUUID(), label: '', required: true }); })}>Add skill input</button><label>Expected skill outputs<textarea rows={2} placeholder="One output description per line" {...describe('manifest.outputs')} value={draft.manifest.outputs.join('\n')} onChange={event => change(value => { value.manifest.outputs = lines(event.target.value); })} /></label>{fieldError('manifest.outputs')}</fieldset>
        <fieldset aria-describedby={fields['manifest.needs'] ? `${formId}-manifest.needs` : undefined}><legend>Tool and effect needs</legend><p>At most 16 tool needs; at most 16 recipients and 16 attachment classifications per need, one identifier per line. Every declared need must be compatible. Unqualified tools remain unavailable. A pure technique can leave this list empty.</p>{draft.manifest.needs.map((need, index) => <div className="methodology-requirement" key={index}><label>Need identifier<input required pattern="(?:[A-Za-z0-9_]|-)+" maxLength={128} {...describe(`manifest.needs.${index}.id`)} value={need.id} onChange={event => change(value => { value.manifest.needs[index]!.id = event.target.value; })} /></label>{fieldError(`manifest.needs.${index}.id`)}<label>Server-owned tool<select value={need.tool} onChange={event => change(value => { value.manifest.needs[index]!.tool = event.target.value as typeof need.tool; })}>{skillTools.map(tool => <option key={tool} value={tool}>{tool}</option>)}</select></label>
          {(['account_id', 'environment_id', 'destination', 'resource_id'] as const).map(field => <div key={field}><label>{field.replaceAll('_', ' ')} (optional narrowing)<input pattern="(?:[A-Za-z0-9_]|-)+" maxLength={128} {...describe(`manifest.needs.${index}.${field}`)} value={need[field] ?? ''} onChange={event => change(value => { value.manifest.needs[index]![field] = event.target.value || null; })} /></label>{fieldError(`manifest.needs.${index}.${field}`)}</div>)}
          <label>Required recipients<textarea rows={2} {...describe(`manifest.needs.${index}.recipients`)} value={need.recipients.join('\n')} onChange={event => change(value => { value.manifest.needs[index]!.recipients = ids(event.target.value); })} /></label>{fieldError(`manifest.needs.${index}.recipients`)}<label>Required attachment classifications<textarea rows={2} {...describe(`manifest.needs.${index}.attachment_classifications`)} value={need.attachment_classifications.join('\n')} onChange={event => change(value => { value.manifest.needs[index]!.attachment_classifications = ids(event.target.value); })} /></label>{fieldError(`manifest.needs.${index}.attachment_classifications`)}<label className="methodology-check"><input type="checkbox" checked={need.requires_attachments} onChange={event => change(value => { value.manifest.needs[index]!.requires_attachments = event.target.checked; })} />Requires attachments</label><button type="button" className="text-button" onClick={() => change(value => { value.manifest.needs.splice(index, 1); })}>Remove need {index + 1}</button></div>)}<button type="button" className="quiet-button" disabled={draft.manifest.needs.length >= 16} onClick={() => change(value => { value.manifest.needs.push({ id: crypto.randomUUID(), tool: 'analysis_v1', account_id: null, environment_id: null, destination: null, resource_id: null, recipients: [], attachment_classifications: [], requires_attachments: false }); })}>Add tool need</button></fieldset>
        <fieldset aria-describedby={fields['manifest.resources'] ? `${formId}-manifest.resources` : undefined}><legend>Immutable text resources</legend><p>At most 16 resources, 32 KiB UTF-8 each and 128 KiB total. Content and line breaks are preserved. Scripts cannot run here.</p>{draft.manifest.resources.map((resource, index) => <div className="methodology-requirement" key={index}><label>Resource identifier<input required pattern="(?:[A-Za-z0-9_]|-)+" maxLength={128} {...describe(`manifest.resources.${index}.id`)} value={resource.id} onChange={event => change(value => { value.manifest.resources[index]!.id = event.target.value; })} /></label>{fieldError(`manifest.resources.${index}.id`)}<label>Resource kind<select value={resource.kind} onChange={event => change(value => { value.manifest.resources[index]!.kind = event.target.value as typeof resource.kind; })}><option value="text">Text resource</option><option value="script">Inert script</option></select></label><label>Resource content<textarea required rows={5} {...describe(`manifest.resources.${index}.content`)} value={resource.content} onChange={event => change(value => { value.manifest.resources[index]!.content = event.target.value; })} /></label>{fieldError(`manifest.resources.${index}.content`)}<button type="button" className="text-button" onClick={() => change(value => { value.manifest.resources.splice(index, 1); })}>Remove resource {index + 1}</button></div>)}<button type="button" className="quiet-button" disabled={draft.manifest.resources.length >= 16} onClick={() => change(value => { value.manifest.resources.push({ id: crypto.randomUUID(), kind: 'text', content: '' }); })}>Add skill resource</button></fieldset>
        <div className="methodology-actions"><button type="submit">Install immutable version</button><button type="button" className="quiet-button" onClick={() => { updateDraft(null); keepDraft(null); setFields({}); setError(''); }}>Cancel skill edit</button></div>
      </fieldset></form> : null}
      {statusDraft && snapshot ? <form className="methodology-editor" aria-label="Change skill status" onSubmit={event => { event.preventDefault(); saveStatus(); }}><fieldset disabled={working || !!pending}><legend>{statusDraft.status === 'recalled' ? 'Recall' : statusDraft.status === 'disabled' ? 'Disable' : 'Enable'} {statusDraft.version.command.manifest.name}</legend><p>{statusDraft.status === 'recalled' ? 'Recall identifies affected selections and prevents further faulty-version use. Historical selections and consumed receipts remain intact.' : 'Current catalog restrictions are checked again for new selections and new use.'}</p>{statusDraft.expected_revision !== snapshot.revision ? <section className="notice"><p>The catalog changed while this status change was open. Review the current version before continuing.</p><button type="button" className="quiet-button" onClick={() => setStatusDraft({ ...statusDraft, expected_revision: snapshot.revision })}>Use latest skill status revision</button></section> : null}<label>Skill status reason<input required {...describe('status_reason')} value={statusDraft.reason} onChange={event => setStatusDraft({ ...statusDraft, reason: event.target.value })} /></label>{fieldError('status_reason')}<button type="submit">Record {statusDraft.status === 'recalled' ? 'skill recall' : statusDraft.status === 'disabled' ? 'skill disable' : 'skill enable'}</button><button type="button" className="quiet-button" onClick={() => { updateStatusDraft(null); keepDraft(null); setFields({}); }}>Cancel status change</button></fieldset></form> : null}
      <section aria-label="Skill catalog versions"><h3>Catalog versions</h3>{snapshot?.versions.length === 0 ? <p>No skills installed. Evidence files and retrieved instructions do not install techniques automatically.</p> : null}{snapshot?.versions.map(version => <article className="methodology-version" key={version.id}><h4>{version.command.manifest.name} · {version.command.manifest.version} · {version.status}</h4><SkillDetails version={version} /><SkillHistory organisation={organisation} version={version} session={session} accessReady={visible} onAccessFailure={withdrawPrivate} /><div className="methodology-actions"><button type="button" className="quiet-button" disabled={working || !!pending} onClick={() => edit(version)}>Edit as new skill version</button>{version.status !== 'recalled' ? <><button type="button" className="quiet-button" disabled={working || !!pending} onClick={() => changeStatus(version, version.status === 'enabled' ? 'disabled' : 'enabled')}>{version.status === 'enabled' ? 'Disable skill version' : 'Enable skill version'}</button><button type="button" className="text-button" disabled={working || !!pending} onClick={() => changeStatus(version, 'recalled')}>Recall skill version</button></> : null}</div></article>)}</section>
    </div>
  </section>;
}

function SkillAssignmentOptions({ organisation, session, accessReady, assignment, onChange, onAccessFailure, describe, fieldError }: {
  organisation: string; session: Session; accessReady: boolean; assignment: InstallSkill['assignment']; onChange: (assignment: InstallSkill['assignment']) => void; onAccessFailure: (error?: AccessError) => void;
  describe: (field: string) => { 'aria-invalid': boolean; 'aria-describedby': string | undefined }; fieldError: (field: string) => ReactNode;
}) {
  const [clientAfter, setClientAfter] = useState<string | null>(null);
  const [engagementAfter, setEngagementAfter] = useState<string | null>(null);
  const owner = skillAudience(session, organisation), client = assignment.client_id ?? null;
  const clientsRead = useCallback((signal: AbortSignal) => readSkillAssignments(organisation, 'client', null, clientAfter, session, signal), [organisation, clientAfter, session.identity.id, session.csrf_token]);
  const engagementsRead = useCallback((signal: AbortSignal) => readSkillAssignments(organisation, 'engagement', client, engagementAfter, session, signal), [organisation, client, engagementAfter, session.identity.id, session.csrf_token]);
  const clients = useSkillInspection<SkillAssignmentPage>(`${owner}/clients/${clientAfter ?? ''}`, accessReady, '', clientsRead, onAccessFailure);
  const engagements = useSkillInspection<SkillAssignmentPage>(`${owner}/engagements/${client ?? ''}/${engagementAfter ?? ''}`, accessReady && assignment.kind === 'engagement' && !!client, '', engagementsRead, onAccessFailure);
  return <>
    {!clients.verified ? <p role="status">{clients.error || 'Checking skill clients…'}</p> : null}
    {clients.error ? <button type="button" onClick={() => void clients.refresh()}>Retry skill clients</button> : null}
    <div hidden={!clients.verified}><label>Skill client<select required disabled={!clients.verified} {...describe('assignment.client_id')} value={client ?? ''} onChange={event => { setEngagementAfter(null); onChange({ ...assignment, client_id: event.target.value || null, engagement_id: null }); }}><option value="">Choose a client</option>{client && !clients.value?.clients.some(item => item.client_id === client) ? <option value={client}>{client} · retained choice</option> : null}{clients.value?.clients.map(item => <option key={item.client_id} value={item.client_id}>{item.client_name}</option>)}</select></label>{fieldError('assignment.client_id')}
      {clientAfter ? <button type="button" className="text-button" disabled={clients.loading} onClick={() => setClientAfter(null)}>First skill clients</button> : null}
      {clients.value?.next_after ? <button type="button" className="text-button" disabled={clients.loading} onClick={() => setClientAfter(clients.value!.next_after ?? null)}>More skill clients</button> : null}
    </div>
    {assignment.kind === 'engagement' ? <>{client && !engagements.verified ? <p role="status">{engagements.error || 'Checking skill engagements…'}</p> : null}{engagements.error ? <button type="button" onClick={() => void engagements.refresh()}>Retry skill engagements</button> : null}<div hidden={!engagements.verified}><label>Skill engagement<select required disabled={!engagements.verified} {...describe('assignment.engagement_id')} value={assignment.engagement_id ?? ''} onChange={event => onChange({ ...assignment, engagement_id: event.target.value || null })}><option value="">Choose an engagement</option>{assignment.engagement_id && !engagements.value?.engagements.some(item => item.engagement_id === assignment.engagement_id) ? <option value={assignment.engagement_id}>{assignment.engagement_id} · retained choice</option> : null}{engagements.value?.engagements.map(item => <option key={item.engagement_id} value={item.engagement_id}>{item.engagement_name}</option>)}</select></label>{fieldError('assignment.engagement_id')}
      {engagementAfter ? <button type="button" className="text-button" disabled={engagements.loading} onClick={() => setEngagementAfter(null)}>First skill engagements</button> : null}
      {engagements.value?.next_after ? <button type="button" className="text-button" disabled={engagements.loading} onClick={() => setEngagementAfter(engagements.value!.next_after ?? null)}>More skill engagements</button> : null}
    </div></> : null}
  </>;
}
function SkillHistory({ organisation, version, session, accessReady, onAccessFailure }: { organisation: string; version: SkillVersion; session: Session; accessReady: boolean; onAccessFailure: (error?: AccessError) => void }) {
  const [open, setOpen] = useState(false), [before, setBefore] = useState<string | null>(null);
  const read = useCallback((signal: AbortSignal) => readSkillStatusHistory(organisation, version.id, before, session, signal), [organisation, version.id, before, session.identity.id, session.csrf_token]);
  const history = useSkillInspection<SkillStatusHistory>(`${skillAudience(session, organisation)}/history/${version.id}/${before ?? ''}`, accessReady && open, version.status_revision, read, onAccessFailure);
  return <details onToggle={event => setOpen(event.currentTarget.open)}><summary>Inspect skill status history</summary>
    {!history.verified ? <p role="status">{history.error || 'Checking recorded skill status changes…'}</p> : null}
    <div hidden={!history.verified}><ol>{history.value?.events.map(event => <li key={event.event_id}><strong>{event.status} · revision {event.revision}</strong><p>Recorded by {event.actor_id} on {new Date(event.recorded_at * 1000).toLocaleString()}</p><p className="retained-text">{event.reason ?? 'Initial installation status'}</p></li>)}</ol>
    {before ? <button type="button" className="text-button" disabled={history.loading} onClick={() => setBefore(null)}>Latest skill status changes</button> : null}
    {history.value?.next_before_revision ? <button type="button" className="text-button" disabled={history.loading} onClick={() => setBefore(history.value!.next_before_revision ?? null)}>Earlier skill status changes</button> : null}
    </div><button type="button" className="text-button" disabled={!accessReady || history.loading} onClick={() => void history.refresh()}>Refresh skill status history</button>
  </details>;
}
