import { defineRailway, preserve, project, service, volume } from 'railway/iac';

/**
 * AD-11: web and worker are separate containers built from this one repository;
 * PostgreSQL 18 is the system of record. Config as Code (railway.json) is
 * deprecated on Railway, so this file is the declared shape of the PoC environment.
 *
 * NOT COMPILED OR TYPECHECKED HERE. `railway` is not a workspace dependency, so
 * `pnpm -r typecheck`, `pnpm boundaries` and `pnpm test` never see this file. Its
 * only validation is `railway config plan` (then `railway config apply`) run against
 * a real Railway workspace. Treat an edit here as unverified until a plan is clean.
 *
 * Secrets stay on Railway; nothing here carries a secret value.
 */
export default defineRailway(() => {
  const data = volume('postgres-data', { sizeMB: 5120 });

  const postgres = service('postgres', {
    source: { image: 'ghcr.io/railwayapp-templates/postgres-ssl:18' },
    volumeMounts: { '/var/lib/postgresql/data': data },
    env: {
      POSTGRES_USER: 'postgres',
      POSTGRES_DB: 'railway',
      PGDATA: '/var/lib/postgresql/data/pgdata',
      PGPORT: '5432',
      // Generated by Railway on first apply and never rewritten from here: replacing
      // it would orphan the volume's existing data directory.
      POSTGRES_PASSWORD: preserve(),
      // A Railway reference string, resolved by the platform at deploy time. It is
      // deliberately not assembled in this file -- the password never leaves Railway.
      DATABASE_URL:
        'postgresql://${{POSTGRES_USER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:5432/${{POSTGRES_DB}}',
    },
  });

  // No `source: { repo, branch }` on web or worker, deliberately. Repository
  // auto-deploy would ship a new build as soon as main moves, which races the
  // release pipeline's migration job and violates AD-15's migrate-then-deploy
  // order. release.yml is the only thing that deploys these, via `railway up`.
  const web = service('web', {
    dockerfile: 'apps/web/Dockerfile',
    start: 'node apps/web/server.js',
    healthcheck: '/api/health',
    env: {
      DATABASE_URL: postgres.env.DATABASE_URL,
      SERVICE_NAME: 'web',
      SCHEMA_RANGE_MIN: '1',
      SCHEMA_RANGE_MAX: '1',
      NODE_ENV: 'production',
      PORT: '3000',
    },
  });

  const worker = service('worker', {
    dockerfile: 'apps/worker/Dockerfile',
    start: 'node dist/main.js',
    env: {
      DATABASE_URL: postgres.env.DATABASE_URL,
      SERVICE_NAME: 'worker',
      SCHEMA_RANGE_MIN: '1',
      SCHEMA_RANGE_MAX: '1',
      NODE_ENV: 'production',
    },
  });

  return project('intellifin-audit', { resources: [postgres, data, web, worker] });
});
