import { defineRailway, preserve, project, service, volume } from 'railway/iac';

/**
 * AD-11: web and worker are separate containers built from this one repository;
 * PostgreSQL 18 is the system of record. Config as Code (railway.json) is
 * deprecated on Railway, so this file is the declared shape of the PoC environment.
 *
 * NOT COMPILED OR TYPECHECKED HERE. `railway` is not a workspace dependency, so
 * `pnpm -r typecheck`, `pnpm boundaries` and `pnpm test` never see this file. Its
 * only validation is `railway config plan` (then `railway config apply`) run against
 * a real Railway workspace. Treat an edit here as unverified until a plan is clean.
 *
 * Secrets stay on Railway; nothing here carries a secret value.
 */
export default defineRailway(() => {
  const data = volume('postgres-data', { sizeMB: 5120 });

  const postgres = service('postgres', {
    source: { image: 'ghcr.io/railwayapp-templates/postgres-ssl:18' },
    volumeMounts: { '/var/lib/postgresql/data': data },
    env: {
      POSTGRES_USER: 'postgres',
      POSTGRES_DB: 'railway',
      PGDATA: '/var/lib/postgresql/data/pgdata',
      PGPORT: '5432',
      // Generated by Railway on first apply and never rewritten from here: replacing
      // it would orphan the volume's existing data directory.
      POSTGRES_PASSWORD: preserve(),
      // A Railway reference string, resolved by the platform at deploy time. It is
      // deliberately not assembled in this file -- the password never leaves Railway.
      DATABASE_URL:
        'postgresql://${{POSTGRES_USER}}:${{POSTGRES_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:5432/${{POSTGRES_DB}}',
    },
  });

  // No `source: { repo, branch }` on web or worker, deliberately. Repository
  // auto-deploy would ship a new build as soon as main moves, which races the
  // release pipeline's migration job and violates AD-15's migrate-then-deploy
  // order. release.yml is the only thing that deploys these, via `railway up`.
  const web = service('web', {
    dockerfile: 'apps/web/Dockerfile',
    start: 'node apps/web/server.js',
    healthcheck: '/api/health',
    env: {
      DATABASE_URL: postgres.env.DATABASE_URL,
      SERVICE_NAME: 'web',
      NODE_ENV: 'production',
      PORT: '3000',
      // Better Auth signs the session cookie with this. It is a secret, so it is set
      // once in the Railway dashboard and preserved here rather than written from
      // code -- the same rule POSTGRES_PASSWORD follows.
      BETTER_AUTH_SECRET: preserve(),
      // The public origin a browser reaches, resolved by Railway at deploy time.
      BETTER_AUTH_URL: 'https://${{RAILWAY_PUBLIC_DOMAIN}}',
      // What this deployment has been told about each credential reference: a JSON
      // object mapping an opaque reference to `read-only` or `write-capable`. It holds
      // NO secret and cannot — that is the whole point of Story 1.6 — so it is declared
      // here rather than preserved from the dashboard.
      //
      // It is declared at all because an absent value is an EMPTY manifest, which
      // refuses every registration with `Audit credentials must be read-only.` — a
      // sentence about the credential, given to an operator whose actual problem is an
      // unconfigured deployment. `{}` is the same refusal, said on purpose.
      //
      // A plain literal, not `preserve()`: it holds no secret, so there is nothing for
      // the dashboard to own. Widen it here when a real reference is issued.
      CREDENTIAL_CAPABILITIES: '{}',
    },
  });

  const worker = service('worker', {
    dockerfile: 'apps/worker/Dockerfile',
    start: 'node dist/main.js',
    env: {
      DATABASE_URL: postgres.env.DATABASE_URL,
      SERVICE_NAME: 'worker',
      NODE_ENV: 'production',
      // Story 3.7. Every Exception is written with a keyed HMAC-SHA-256 fingerprint, and
      // this is that key. A SECRET, so it is set once in the Railway dashboard and
      // preserved here rather than written from code -- the BETTER_AUTH_SECRET rule. It is
      // the WORKER'S alone: only the worker evaluates a compiled condition, and
      // `loadConfig` refuses a production web container that carries it.
      //
      // Absent, adapter execution is disabled and says so by name, exactly as an absent
      // CREDENTIAL_TOKENS disables it. That is deliberate: an Exception with no fingerprint
      // is a permanent row nobody can later check, and a worker that refused to BOOT would
      // stop plan derivation, notification delivery and the liveness row as well.
      EXCEPTION_FINGERPRINT_KEY: preserve(),
      // The label retained beside every fingerprint, so a rotated key still says which key
      // signed which row. It carries no secret, so it is declared here rather than
      // preserved. Change it in the SAME apply that rotates the key.
      EXCEPTION_FINGERPRINT_KEY_ID: 'k1',
      // Story 4.1. The managed remote browser the Agent Workspace runs in. A SECRET, set
      // once in the Railway dashboard and preserved here rather than written from code --
      // the BETTER_AUTH_SECRET rule again. The WORKER'S alone: only the worker provisions a
      // workspace, and `loadConfig` refuses a production web container that carries it.
      //
      // Absent, the workspace falls back to a LOCAL Chromium rather than refusing to boot.
      // That is not an equivalent: local isolates browser state per Run and does NOT
      // isolate the worker process, and egress is policed inside the browser rather than at
      // the network. Every workspace row records which mode it actually had.
      SOLARI_API_KEY: preserve(),
      // Session recording, which Epic 5's replay reads. It carries no secret, so it is
      // declared here rather than preserved. It can ONLY be set at session creation -- the
      // replay endpoint 404s forever for a session created without it -- so turning it on
      // applies to Runs made after the change and never to Runs already recorded.
      SOLARI_RECORDING: 'false',
      // Stories 3.2 to 3.5. The PRIVATE S3-compatible bucket every Evidence artifact is
      // frozen into. All five together or none: `loadConfig` refuses a partial set. Absent,
      // the worker starts, logs `Population execution disabled` and ends every Run
      // RUN_FAILED with a closed diagnostic rather than fabricating a Run nobody can read.
      // Endpoint, region and bucket carry no secret but are this deployment's to name.
      EVIDENCE_S3_ENDPOINT: preserve(),
      EVIDENCE_S3_REGION: preserve(),
      EVIDENCE_S3_BUCKET: preserve(),
      EVIDENCE_S3_ACCESS_KEY_ID: preserve(),
      EVIDENCE_S3_SECRET_ACCESS_KEY: preserve(),
      // Story 3.3. The JSON manifest from opaque credential reference to token value; the
      // WORKER'S alone, and a production web container that carries it refuses to start.
      // Absent, adapter and agent extraction are disabled by name. Two keys that trim to
      // one reference refuse the whole manifest.
      CREDENTIAL_TOKENS: preserve(),
      // Epic 4. The agent model gateway: Anthropic is primary when both keys are present,
      // OpenAI the fallback; the model ids override the build's defaults and are the
      // owner's deliberate choice, so they are preserved rather than written from code.
      ANTHROPIC_API_KEY: preserve(),
      OPENAI_API_KEY: preserve(),
      AGENT_ANTHROPIC_MODEL: preserve(),
      AGENT_OPENAI_MODEL: preserve(),
    },
  });

  /**
   * The synthetic Northstar systems (Story 1.8).
   *
   * No database, no credential, no volume: it serves fixture files that ship inside its
   * own image. It is read-only at the system level (FR-3) — every method but GET and
   * HEAD is refused above routing — so a public origin exposes synthetic data that
   * nobody, including us, can change through it.
   *
   * It is deliberately NOT given `DATABASE_URL`. A Target System that can reach the
   * audit platform's own database is not a Target System; it is part of the platform.
   *
   * One service, six path-prefixed systems. Each registration's allowed origin is this
   * service's public domain plus its prefix (`/loancore`, `/accessgate`, …), so the
   * agent's allowlist still names six origins.
   */
  const northstar = service('northstar', {
    dockerfile: 'apps/northstar/Dockerfile',
    start: 'node dist/main.js',
    healthcheck: '/health',
    env: {
      SERVICE_NAME: 'northstar',
      NODE_ENV: 'production',
      // Railway injects PORT; `main.ts` prefers NORTHSTAR_PORT and falls back to it.
      PORT: '4300',
    },
  });

  return project('intellifin-audit', {
    resources: [postgres, data, web, worker, northstar],
  });
});
