[package]
name = "zobba-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
zobba-domain.workspace = true
zobba-application.workspace = true
sqlx.workspace = true
tokio.workspace = true
url.workspace = true

[lints]
workspace = true
