# /// script
# requires-python = ">=3.11"
# dependencies = ["rfc8785==0.1.4"]
# ///
"""Produce tests/fixtures/observation-digest-golden.json.

The point of this script is that it is NOT TypeScript. `packages/domain/src/runs/
observation.ts` computes the Observation digest, and a fixture generated by that code
would only prove the code equals itself. Everything here — the thirteen-key envelope,
the RFC 8785 canonical bytes and the SHA-256 — is produced by an independent
implementation: `rfc8785` from PyPI and the standard library's `hashlib`.

The envelopes below are written out BY HAND rather than derived from the wire record by
a Python copy of the projection rule. That is deliberate: the projection (which wire key
becomes which snake_case envelope key, and which fields are deliberately absent) is
exactly the part a shared helper would stop checking. A reviewer can read each
`envelope` and see the thirteen keys.

What the digest covers and what it must not:

  * it covers the WIRE RECORD, all thirteen §B.1 keys including `observationId`,
    every attribute's grounding and every attribute's corroboration;
  * it covers NOTHING operational. There is no attempt counter, lease, revision, row
    version, coverage state or registration time in the envelope, because those change
    for reasons that have nothing to do with what was observed, and a digest that moved
    with them would make an untouched row look tampered with.

Run it from the repository root:

    uv run scripts/make-observation-digest-golden.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

import rfc8785

OUT = (
    pathlib.Path(__file__).resolve().parent.parent
    / "tests"
    / "fixtures"
    / "observation-digest-golden.json"
)

WORK_ITEM = "01990000-0000-7000-8000-00000000a001"
STEP_EXECUTION = "01990000-0000-7000-8000-00000000b001"
EVIDENCE = "01990000-0000-7000-8000-00000000c001"

# A grounded identity attribute, as the wire record carries it and as the envelope
# projects it. Written twice on purpose: the projection is the thing being checked.
FOUND_RECORD = {
    "schemaVersion": 1,
    "observationId": "0f9a1a3d-2f2c-8a1b-9f0c-6b4e2d1c8a70",
    "workItemId": WORK_ITEM,
    "populationRecordKey": "AG-1003",
    "targetSystem": "accessgate",
    "found": "true",
    "observedAt": "2026-09-05T00:00:00.000Z",
    "stepExecutionId": STEP_EXECUTION,
    "captureMethod": "adapter",
    "matchOrigin": "platform",
    "identity": {
        "name": "account_id",
        "originalValue": "AG-1003",
        "normalizedValue": "AG-1003",
        "grounding": {
            "evidenceId": EVIDENCE,
            "locator": "$.accounts[1].account_id",
            "label": "account_id",
            "extractedText": "AG-1003",
        },
        "corroboration": None,
    },
    "attributes": [
        {
            "name": "roles",
            "originalValue": ["VENDOR_MAINTAINER", "VENDOR_APPROVER"],
            "normalizedValue": ["VENDOR_MAINTAINER", "VENDOR_APPROVER"],
            "grounding": {
                "evidenceId": EVIDENCE,
                "locator": "$.accounts[1].roles",
                "label": "roles",
                "extractedText": '["VENDOR_MAINTAINER","VENDOR_APPROVER"]',
            },
            "corroboration": None,
        },
    ],
    "evidenceIds": [EVIDENCE],
}

FOUND_ENVELOPE = {
    "attributes": [
        {
            "corroboration": None,
            "grounding": {
                "evidence_id": EVIDENCE,
                "extracted_text": '["VENDOR_MAINTAINER","VENDOR_APPROVER"]',
                "label": "roles",
                "locator": "$.accounts[1].roles",
            },
            "name": "roles",
            "normalized_value": ["VENDOR_MAINTAINER", "VENDOR_APPROVER"],
            "original_value": ["VENDOR_MAINTAINER", "VENDOR_APPROVER"],
        },
    ],
    "capture_method": "adapter",
    "evidence_ids": [EVIDENCE],
    "found": "true",
    "identity": {
        "corroboration": None,
        "grounding": {
            "evidence_id": EVIDENCE,
            "extracted_text": "AG-1003",
            "label": "account_id",
            "locator": "$.accounts[1].account_id",
        },
        "name": "account_id",
        "normalized_value": "AG-1003",
        "original_value": "AG-1003",
    },
    "match_origin": "platform",
    "observation_id": "0f9a1a3d-2f2c-8a1b-9f0c-6b4e2d1c8a70",
    "observed_at": "2026-09-05T00:00:00.000Z",
    "population_record_key": "AG-1003",
    "schema_version": 1,
    "step_execution_id": STEP_EXECUTION,
    "target_system": "accessgate",
    "work_item_id": WORK_ITEM,
}


def corroborated(record: dict, verdict: str) -> dict:
    """The same record after the Evidence Quality Gate judged its attributes."""
    copy = json.loads(json.dumps(record))
    copy["identity"]["corroboration"] = verdict
    for attribute in copy["attributes"]:
        attribute["corroboration"] = verdict
    return copy


def corroborated_envelope(envelope: dict, verdict: str) -> dict:
    copy = json.loads(json.dumps(envelope))
    copy["identity"]["corroboration"] = verdict
    for attribute in copy["attributes"]:
        attribute["corroboration"] = verdict
    return copy


# (name, note, wire record as the domain module receives it, hand-written envelope)
VECTORS: list[tuple[str, str, dict, dict]] = [
    (
        "found-grounded-identity",
        "A resolved match: a grounded identity attribute, one grounded declared "
        "attribute whose value is an array, and one linked Evidence item. Every "
        "grounding is projected under snake_case keys, and `corroboration` is null "
        "because nothing has judged it yet — null means 'not yet judged' and never "
        "'matched'.",
        FOUND_RECORD,
        FOUND_ENVELOPE,
    ),
    (
        "found-after-corroboration",
        "The same Observation after the Evidence Quality Gate set corroboration on "
        "every attribute. Its digest MUST differ from the vector above: corroboration "
        "is set at registration and is part of the record the digest covers, which is "
        "why corroboration runs before the digest is taken and never after.",
        corroborated(FOUND_RECORD, "matched"),
        corroborated_envelope(FOUND_ENVELOPE, "matched"),
    ),
    (
        "absent-no-identity",
        "A proven-absence candidate. `identity` is null and there are no attributes, "
        "because an absent Observation that carried either would be asserting the match "
        "it exists to say did not resolve. The absence PROOF is deliberately absent from "
        "the envelope: it is registration evidence, not the wire record, and the "
        "coverage state derived from it is a column beside the row rather than a "
        "hashed field.",
        {
            "schemaVersion": 1,
            "observationId": "2c7b5f11-0a8e-8d42-b1a7-3e5c9d0f7a21",
            "workItemId": WORK_ITEM,
            "populationRecordKey": "AG-9999",
            "targetSystem": "accessgate",
            "found": "false",
            "observedAt": "2026-09-05T00:00:00.000Z",
            "stepExecutionId": STEP_EXECUTION,
            "captureMethod": "adapter",
            "matchOrigin": "platform",
            "identity": None,
            "attributes": [],
            "evidenceIds": [EVIDENCE],
        },
        {
            "attributes": [],
            "capture_method": "adapter",
            "evidence_ids": [EVIDENCE],
            "found": "false",
            "identity": None,
            "match_origin": "platform",
            "observation_id": "2c7b5f11-0a8e-8d42-b1a7-3e5c9d0f7a21",
            "observed_at": "2026-09-05T00:00:00.000Z",
            "population_record_key": "AG-9999",
            "schema_version": 1,
            "step_execution_id": STEP_EXECUTION,
            "target_system": "accessgate",
            "work_item_id": WORK_ITEM,
        },
    ),
    (
        "ambiguous-no-identity",
        "More than one candidate. Byte-identical to the absent vector except for "
        "`found` and the Observation id, so its digest proves the `found` value is "
        "hashed rather than folded into a boolean.",
        {
            "schemaVersion": 1,
            "observationId": "6b1d0e44-5c3a-8f19-8c22-9a7f4b2e6d03",
            "workItemId": WORK_ITEM,
            "populationRecordKey": "AG-1007",
            "targetSystem": "accessgate",
            "found": "ambiguous",
            "observedAt": "2026-09-05T00:00:00.000Z",
            "stepExecutionId": STEP_EXECUTION,
            "captureMethod": "adapter",
            "matchOrigin": "platform",
            "identity": None,
            "attributes": [],
            "evidenceIds": [EVIDENCE],
        },
        {
            "attributes": [],
            "capture_method": "adapter",
            "evidence_ids": [EVIDENCE],
            "found": "ambiguous",
            "identity": None,
            "match_origin": "platform",
            "observation_id": "6b1d0e44-5c3a-8f19-8c22-9a7f4b2e6d03",
            "observed_at": "2026-09-05T00:00:00.000Z",
            "population_record_key": "AG-1007",
            "schema_version": 1,
            "step_execution_id": STEP_EXECUTION,
            "target_system": "accessgate",
            "work_item_id": WORK_ITEM,
        },
    ),
    (
        "attribute-order-is-hashed",
        "The found vector with a second declared attribute, given in the order the "
        "frozen plan declares. Attributes are a LIST, not a set: `[roles, status]` and "
        "`[status, roles]` are different records, because the plan declares an order "
        "and a reader told the other one reads the wrong field. The reversed pair is "
        "the next vector, and the two digests must differ.",
        {
            **FOUND_RECORD,
            "observationId": "8e0c2a77-1b6d-8e55-a0f3-7c1b5e9d4a62",
            "attributes": [
                FOUND_RECORD["attributes"][0],
                {
                    "name": "status",
                    "originalValue": "Active",
                    "normalizedValue": "Active",
                    "grounding": {
                        "evidenceId": EVIDENCE,
                        "locator": "$.accounts[1].status",
                        "label": "status",
                        "extractedText": "Active",
                    },
                    "corroboration": None,
                },
            ],
        },
        {
            **FOUND_ENVELOPE,
            "observation_id": "8e0c2a77-1b6d-8e55-a0f3-7c1b5e9d4a62",
            "attributes": [
                FOUND_ENVELOPE["attributes"][0],
                {
                    "corroboration": None,
                    "grounding": {
                        "evidence_id": EVIDENCE,
                        "extracted_text": "Active",
                        "label": "status",
                        "locator": "$.accounts[1].status",
                    },
                    "name": "status",
                    "normalized_value": "Active",
                    "original_value": "Active",
                },
            ],
        },
    ),
    (
        "attribute-order-reversed",
        "The vector above with its two attributes swapped and nothing else changed. "
        "Its digest must DIFFER. This is the vector that fails if attributes are ever "
        "sorted before hashing.",
        {
            **FOUND_RECORD,
            "observationId": "8e0c2a77-1b6d-8e55-a0f3-7c1b5e9d4a62",
            "attributes": [
                {
                    "name": "status",
                    "originalValue": "Active",
                    "normalizedValue": "Active",
                    "grounding": {
                        "evidenceId": EVIDENCE,
                        "locator": "$.accounts[1].status",
                        "label": "status",
                        "extractedText": "Active",
                    },
                    "corroboration": None,
                },
                FOUND_RECORD["attributes"][0],
            ],
        },
        {
            **FOUND_ENVELOPE,
            "observation_id": "8e0c2a77-1b6d-8e55-a0f3-7c1b5e9d4a62",
            "attributes": [
                {
                    "corroboration": None,
                    "grounding": {
                        "evidence_id": EVIDENCE,
                        "extracted_text": "Active",
                        "label": "status",
                        "locator": "$.accounts[1].status",
                    },
                    "name": "status",
                    "normalized_value": "Active",
                    "original_value": "Active",
                },
                FOUND_ENVELOPE["attributes"][0],
            ],
        },
    ),
    (
        "unicode-and-leading-zeros",
        "A multi-byte label, an astral-plane character in an extracted value, and a "
        "population key with leading zeros. RFC 8785 sorts object keys by UTF-16 code "
        "unit and emits characters unescaped; §B requires leading zeros to survive, so "
        "`000123` is hashed as the string it is and never as a number.",
        {
            "schemaVersion": 1,
            "observationId": "3a5e7c99-4d2b-8b07-bf14-2e8d6a0c9b55",
            "workItemId": WORK_ITEM,
            "populationRecordKey": "000123",
            "targetSystem": "accessgate",
            "found": "true",
            "observedAt": "2026-09-05T12:34:56.789Z",
            "stepExecutionId": STEP_EXECUTION,
            "captureMethod": "agent",
            "matchOrigin": "human-matched",
            "identity": {
                "name": "N° de pièce",
                "originalValue": "000123",
                "normalizedValue": "000123",
                "grounding": {
                    "evidenceId": EVIDENCE,
                    "locator": "$.金額[0].N° de pièce",
                    "label": "N° de pièce",
                    "extractedText": "🔎 000123",
                },
                "corroboration": "model-read",
            },
            "attributes": [],
            "evidenceIds": [EVIDENCE],
        },
        {
            "attributes": [],
            "capture_method": "agent",
            "evidence_ids": [EVIDENCE],
            "found": "true",
            "identity": {
                "corroboration": "model-read",
                "grounding": {
                    "evidence_id": EVIDENCE,
                    "extracted_text": "🔎 000123",
                    "label": "N° de pièce",
                    "locator": "$.金額[0].N° de pièce",
                },
                "name": "N° de pièce",
                "normalized_value": "000123",
                "original_value": "000123",
            },
            "match_origin": "human-matched",
            "observation_id": "3a5e7c99-4d2b-8b07-bf14-2e8d6a0c9b55",
            "observed_at": "2026-09-05T12:34:56.789Z",
            "population_record_key": "000123",
            "schema_version": 1,
            "step_execution_id": STEP_EXECUTION,
            "target_system": "accessgate",
            "work_item_id": WORK_ITEM,
        },
    ),
]

THIRTEEN_KEYS = {
    "attributes",
    "capture_method",
    "evidence_ids",
    "found",
    "identity",
    "match_origin",
    "observation_id",
    "observed_at",
    "population_record_key",
    "schema_version",
    "step_execution_id",
    "target_system",
    "work_item_id",
}

# The batch digest, over the ordered list of per-Observation digests. It is what detects
# a removed row, a reordered batch or an edited stored digest — none of which a per-row
# digest can see, because each surviving row still agrees with itself.
BATCHES: list[tuple[str, str, list[str]]] = [
    ("empty", "No Observations registered. A digest over the empty list.", []),
    (
        "three-in-order",
        "The first three vectors in registration order.",
        ["found-grounded-identity", "absent-no-identity", "ambiguous-no-identity"],
    ),
    (
        "three-reordered",
        "The same three digests in a different order. Its batch digest must DIFFER: "
        "order is part of what the event records.",
        ["absent-no-identity", "found-grounded-identity", "ambiguous-no-identity"],
    ),
]


def main() -> int:
    vectors = []
    for name, note, record, envelope in VECTORS:
        if set(envelope) != THIRTEEN_KEYS:
            raise SystemExit(f"{name}: envelope must hold exactly the thirteen wire keys")
        if (envelope["found"] == "true") != (envelope["identity"] is not None):
            raise SystemExit(f"{name}: a grounded identity is required exactly when found is true")
        canonical = rfc8785.dumps(envelope)
        vectors.append(
            {
                "name": name,
                "note": note,
                "record": record,
                "envelope": envelope,
                "canonicalText": canonical.decode("utf-8"),
                "digest": hashlib.sha256(canonical).hexdigest(),
            }
        )

    by_name = {vector["name"]: vector["digest"] for vector in vectors}
    # Every distinct envelope must have a distinct digest, or a vector proves nothing.
    if len({vector["digest"] for vector in vectors}) != len(vectors):
        raise SystemExit("two different envelopes share a digest; the fixture would prove nothing")

    batches = []
    for name, note, members in BATCHES:
        digests = [by_name[member] for member in members]
        canonical = rfc8785.dumps(digests)
        batches.append(
            {
                "name": name,
                "note": note,
                "members": members,
                "digests": digests,
                "canonicalText": canonical.decode("utf-8"),
                "batchDigest": hashlib.sha256(canonical).hexdigest(),
            }
        )
    if batches[1]["batchDigest"] == batches[2]["batchDigest"]:
        raise SystemExit("a reordered batch produced the same digest; order is not hashed")

    fixture = {
        "producer": f"Python {sys.version.split()[0]} + rfc8785 0.1.4 + hashlib.sha256",
        "producedBy": "scripts/make-observation-digest-golden.py",
        "regenerateWith": "uv run scripts/make-observation-digest-golden.py",
        "why": (
            "Observation digest vectors, produced by an implementation that is NOT the "
            "code under test. packages/domain/src/runs/observation.ts is checked "
            "against these bytes; a fixture produced by that module would prove only "
            "that it equals itself. The envelopes in the generator are written out by "
            "hand, so the projection from a wire record to its thirteen hashed keys is "
            "checked too, not just the hash of an envelope this repository derived."
        ),
        "algorithm": (
            "digest = SHA-256( RFC 8785 canonical JSON of the thirteen-key envelope "
            "{attributes, capture_method, evidence_ids, found, identity, match_origin, "
            "observation_id, observed_at, population_record_key, schema_version, "
            "step_execution_id, target_system, work_item_id} ), lower-case hex. "
            "Attributes keep their declared order. No operational field — attempt, "
            "lease, revision, row version, coverage, registration time — is in the "
            "envelope. batchDigest = SHA-256( RFC 8785 canonical JSON of the ordered "
            "list of per-Observation digests )."
        ),
        "vectors": vectors,
        "batches": batches,
    }
    OUT.write_text(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(vectors)} vectors and {len(batches)} batches")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
