# /// script
# requires-python = ">=3.11"
# dependencies = ["rfc8785==0.1.4"]
# ///
"""Produce tests/fixtures/registration-digest-golden.json.

The point of this script is that it is NOT TypeScript. `packages/domain/src/registrations/
target-system.ts` computes the AD-2 registration digest, and a fixture generated by that
code would only prove the code equals itself. Everything here — the six-key envelope, the
RFC 8785 canonical bytes, and the SHA-256 — is produced by an independent implementation:
`rfc8785` from PyPI and the standard library's `hashlib`.

The envelopes below are written out BY HAND rather than derived from the inputs by a
Python copy of the projection rule. That is deliberate: the projection (which key holds
what, and how the sets are normalized) is exactly the part a shared helper would stop
checking. A reviewer can read each `envelope` and see that it is the six keys AD-2 names.

Run it from the repository root:

    uv run scripts/make-registration-digest-golden.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

import rfc8785

OUT = pathlib.Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "registration-digest-golden.json"

# (name, note, digest input as the domain module receives it, hand-written envelope)
VECTORS: list[tuple[str, str, dict, dict]] = [
    (
        "web-two-origins",
        "A web system. Origins are a set: they are given here out of order and with a "
        "duplicate, and the envelope holds them sorted and deduplicated.",
        {
            "kind": "web",
            "allowedOrigins": [
                "https://northstar.synthetic.invalid",
                "https://alpha.synthetic.invalid",
                "https://northstar.synthetic.invalid",
            ],
            "applicationIdentity": "",
            "credentialRef": "cred://synthetic/northstar-readonly",
            "permittedActions": ["read-attribute", "navigate", "open-record"],
            "attributeLabelPatterns": ["Invoice *", "Approved by"],
            "secondaryKey": "branch-042",
        },
        {
            "allowed_origins": [
                "https://alpha.synthetic.invalid",
                "https://northstar.synthetic.invalid",
            ],
            "attribute_label_patterns": ["Approved by", "Invoice *"],
            "credential_ref": "cred://synthetic/northstar-readonly",
            "kind": "web",
            "permitted_actions": ["navigate", "open-record", "read-attribute"],
            "secondary_key": "branch-042",
        },
    ),
    (
        "desktop-application-identity",
        "A desktop system. The application identity occupies the origins slot, so the "
        "envelope still has all six keys and the same shape as every other kind.",
        {
            "kind": "desktop",
            "allowedOrigins": [],
            "applicationIdentity": "com.synthetic.northstar.ledger",
            "credentialRef": "cred://synthetic/ledger-readonly",
            "permittedActions": ["read-attribute", "capture-screenshot"],
            "attributeLabelPatterns": ["Voucher no."],
            "secondaryKey": "",
        },
        {
            "allowed_origins": ["com.synthetic.northstar.ledger"],
            "attribute_label_patterns": ["Voucher no."],
            "credential_ref": "cred://synthetic/ledger-readonly",
            "kind": "desktop",
            "permitted_actions": ["capture-screenshot", "read-attribute"],
            "secondary_key": None,
        },
    ),
    (
        "api-empty-optional-fields",
        "An API system with no label patterns and no secondary key. Every key is still "
        "present: an absent value is null or an empty list, never a missing key.",
        {
            "kind": "api",
            "allowedOrigins": ["https://api.synthetic.invalid"],
            "applicationIdentity": "",
            "credentialRef": "cred://synthetic/api-readonly",
            "permittedActions": ["read-metadata"],
            "attributeLabelPatterns": [],
            "secondaryKey": "   ",
        },
        {
            "allowed_origins": ["https://api.synthetic.invalid"],
            "attribute_label_patterns": [],
            "credential_ref": "cred://synthetic/api-readonly",
            "kind": "api",
            "permitted_actions": ["read-metadata"],
            "secondary_key": None,
        },
    ),
    (
        "versioned-file-unicode",
        "A versioned file whose locator and labels are multi-byte UTF-8. RFC 8785 sorts "
        "object keys by UTF-16 code unit and emits the characters unescaped, so this "
        "list members are sorted the same way by the domain module, which is why the astral-plane emoji sorts AFTER the CJK character here.",
        {
            "kind": "versioned-file",
            "allowedOrigins": ["s3://synthetic-bucket/ledgers/2026/Qé.csv"],
            "applicationIdentity": "",
            "credentialRef": "cred://synthetic/file-readonly",
            "permittedActions": ["read-file", "read-metadata", "read-file"],
            "attributeLabelPatterns": ["N° de pièce", "金額", "🔎 locator"],
            "secondaryKey": "édition-2",
        },
        {
            "allowed_origins": ["s3://synthetic-bucket/ledgers/2026/Qé.csv"],
            # UTF-16 code-unit order, which is what the domain module's sort produces:
            # "N" U+004E, then U+91D1, then the U+D83D surrogate that begins U+1F50E.
            "attribute_label_patterns": ["N° de pièce", "金額", "🔎 locator"],
            "credential_ref": "cred://synthetic/file-readonly",
            "kind": "versioned-file",
            "permitted_actions": ["read-file", "read-metadata"],
            "secondary_key": "édition-2",
        },
    ),
    (
        "web-same-fields-different-kind",
        "Byte-identical to the first vector except for `kind`. Its digest must differ: "
        "the kind is inside the envelope, not metadata beside it.",
        {
            "kind": "api",
            "allowedOrigins": [
                "https://northstar.synthetic.invalid",
                "https://alpha.synthetic.invalid",
            ],
            "applicationIdentity": "",
            "credentialRef": "cred://synthetic/northstar-readonly",
            "permittedActions": ["read-attribute", "navigate", "open-record"],
            "attributeLabelPatterns": ["Invoice *", "Approved by"],
            "secondaryKey": "branch-042",
        },
        {
            "allowed_origins": [
                "https://alpha.synthetic.invalid",
                "https://northstar.synthetic.invalid",
            ],
            "attribute_label_patterns": ["Approved by", "Invoice *"],
            "credential_ref": "cred://synthetic/northstar-readonly",
            "kind": "api",
            "permitted_actions": ["navigate", "open-record", "read-attribute"],
            "secondary_key": "branch-042",
        },
    ),
]

SIX_KEYS = {
    "allowed_origins",
    "attribute_label_patterns",
    "credential_ref",
    "kind",
    "permitted_actions",
    "secondary_key",
}


def main() -> int:
    vectors = []
    for name, note, digest_input, envelope in VECTORS:
        if set(envelope) != SIX_KEYS:
            raise SystemExit(f"{name}: envelope must hold exactly the six AD-2 keys")
        canonical = rfc8785.dumps(envelope)
        vectors.append(
            {
                "name": name,
                "note": note,
                "input": digest_input,
                "envelope": envelope,
                "canonicalText": canonical.decode("utf-8"),
                "digest": hashlib.sha256(canonical).hexdigest(),
            }
        )

    digests = [vector["digest"] for vector in vectors]
    if len(set(digests)) != len(digests):
        raise SystemExit("two vectors share a digest; the fixture would prove nothing")

    fixture = {
        "producer": f"Python {sys.version.split()[0]} + rfc8785 0.1.4 + hashlib.sha256",
        "producedBy": "scripts/make-registration-digest-golden.py",
        "regenerateWith": "uv run scripts/make-registration-digest-golden.py",
        "why": (
            "AD-2 digest vectors, produced by an implementation that is NOT the code "
            "under test. packages/domain/src/registrations/target-system.ts is checked "
            "against these bytes; a fixture produced by that module would prove only "
            "that it equals itself. The envelopes in the generator are written out by "
            "hand, so the projection from a registration to its six hashed keys is "
            "checked too, not just the hash of an envelope this repository derived."
        ),
        "algorithm": (
            "digest = SHA-256( RFC 8785 canonical JSON of the six-key envelope ), "
            "lower-case hex. No previous-hash prefix: that belongs to the audit chain, "
            "not to this digest."
        ),
        "vectors": vectors,
    }
    OUT.write_text(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(vectors)} vectors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
