# /// script
# requires-python = ">=3.11"
# dependencies = ["rfc8785==0.1.4"]
# ///
"""Produce tests/fixtures/snapshot-extraction-golden.json.

The point of this script is that it is NOT TypeScript.
`packages/domain/src/runs/structural-snapshot.ts` re-reads a stored Structural Snapshot
and says whether an Observation's attribute is `matched` or `contradictory`; a fixture
generated by that module would prove only that it equals itself, which is precisely no
evidence at all for an extractor whose whole job is to be a second opinion.

Everything below is an independent implementation:

  * the locator grammar `$.<collection>[<index>].<field>`, parsed by a regex written here;
  * the `sheet` read — Python's own `csv` module, the `# SYNTHETIC` marker line dropped,
    the header row taken as the label rule;
  * the `json` read — Python's `json`, the collection taken from the envelope, the
    property key taken as the label rule;
  * the value comparison — `rfc8785` from PyPI, the same canonicalization the TypeScript
    uses and a different implementation of it;
  * the UTC normalization — `datetime`, which refuses an impossible calendar date rather
    than rolling it over the way `Date.parse` does.

The `sheet` snapshot is the REAL `fixtures/northstar/generated/role-matrix.csv`, read off
disk and embedded verbatim, so the vectors are taken over bytes a synthetic Target System
actually serves — including the leading `entry` ordinal that keeps two conflicting policy
entries for one role distinguishable.

Run it from the repository root:

    uv run scripts/make-snapshot-extraction-golden.py
"""

from __future__ import annotations

import csv
import io
import json
import pathlib
import re
import sys
from datetime import datetime, timedelta, timezone

import rfc8785

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "tests" / "fixtures" / "snapshot-extraction-golden.json"
ROLE_MATRIX = ROOT / "fixtures" / "northstar" / "generated" / "role-matrix.csv"

VALUE_LIMIT = 8192
SHEET_COLLECTION = "rows"
LOCATOR = re.compile(r"^\$\.([^.\[\]]+)\[(0|[1-9][0-9]*)\]\.([^.\[\]]+)$")
INSTANT = re.compile(
    r"^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?(Z|[+-]\d{2}:\d{2})$"
)


# --------------------------------------------------------------------- the re-read ---


def read_sheet(text: str) -> tuple[list[str], list[dict[str, str]]]:
    """Header cells and data rows, the marker line dropped."""
    records = [row for row in csv.reader(io.StringIO(text), lineterminator="\n") if row]
    if records and records[0] and records[0][0].startswith("# SYNTHETIC"):
        records = records[1:]
    headers = records[0]
    rows = [dict(zip(headers, values, strict=True)) for values in records[1:]]
    return headers, rows


def read_json(text: str) -> dict[str, list[dict]]:
    envelope = json.loads(text)
    return {
        key: value
        for key, value in envelope.items()
        if isinstance(value, list) and all(isinstance(item, dict) for item in value)
    }


def cell(snapshot: dict, locator_text: str):
    """The value at a locator and the substrate's label for it, or None."""
    match = LOCATOR.match(locator_text)
    if match is None:
        return None
    collection, index, field = match.group(1), int(match.group(2)), match.group(3)
    if snapshot["substrate"] == "sheet":
        if collection != SHEET_COLLECTION:
            return None
        headers, rows = read_sheet(snapshot["text"])
        if index >= len(rows) or field not in headers or field not in rows[index]:
            return None
        # The label rule for a sheet is the HEADER CELL.
        return {"value": rows[index][field], "label": headers[headers.index(field)]}
    collections = read_json(snapshot["text"])
    if collection not in collections:
        return None
    rows = collections[collection]
    if index >= len(rows) or field not in rows[index]:
        return None
    # The label rule for JSON is the PROPERTY KEY.
    return {"value": rows[index][field], "label": next(k for k in rows[index] if k == field)}


# ------------------------------------------------------------------- the comparison ---


def canonical(value) -> str:
    return rfc8785.dumps(value).decode("utf-8")


def grounded_text(value) -> str:
    text = value if isinstance(value, str) else canonical(value)
    return text[:VALUE_LIMIT]


def utc(value) -> str | None:
    """The UTC instant of an ISO 8601 date-time, or None. Never rolls a date over."""
    if not isinstance(value, str):
        return None
    match = INSTANT.match(value)
    if match is None:
        return None
    year, month, day, hour, minute, second = (int(match.group(i)) for i in range(1, 7))
    fraction = match.group(7)
    zone = match.group(8)
    milliseconds = 0 if fraction is None else int(fraction.ljust(3, "0"))
    offset = timedelta()
    if zone != "Z":
        sign = -1 if zone.startswith("-") else 1
        hours, minutes = int(zone[1:3]), int(zone[4:6])
        if hours > 23 or minutes > 59:
            return None
        offset = sign * timedelta(hours=hours, minutes=minutes)
    try:
        stamp = datetime(
            year, month, day, hour, minute, second, milliseconds * 1000, tzinfo=timezone.utc
        )
    except ValueError:
        return None
    stamp -= offset
    return stamp.strftime("%Y-%m-%dT%H:%M:%S.") + f"{stamp.microsecond // 1000:03d}Z"


def judge(snapshot: dict, attribute: dict) -> tuple[str | None, str | None]:
    """(corroboration, failure) for one grounded attribute against one snapshot."""
    grounding = attribute["grounding"]
    found = cell(snapshot, grounding["locator"])
    if found is None:
        return "contradictory", "locator-unresolved"
    if found["label"] != grounding["label"]:
        return "contradictory", "label-drift"
    if canonical(found["value"]) != canonical(attribute["originalValue"]):
        return "contradictory", "value-contradicted"
    if grounded_text(found["value"]) != grounding["extractedText"]:
        return "contradictory", "extracted-text-contradicted"
    normalized = canonical(attribute["normalizedValue"])
    authorized = normalized == canonical(found["value"]) or (
        isinstance(found["value"], str)
        and utc(found["value"]) is not None
        and normalized == canonical(utc(found["value"]))
    )
    if not authorized:
        return "contradictory", "normalization-unauthorized"
    return "matched", None


# ------------------------------------------------------------------------ the cases ---

EVIDENCE = "01990000-0000-7000-8000-00000000c001"

ACCOUNTS = json.dumps(
    {
        "synthetic": {"marker": "SYNTHETIC-NORTHSTAR-FIXTURE"},
        "schema_version": 1,
        "representation": "population-rows-v1",
        "source": "accounts",
        "complete": True,
        "returned": 3,
        "schema": ["account_id", "roles", "status", "opened_at"],
        "accounts": [
            {
                "account_id": "AG-1001",
                "roles": ["AP_CLERK"],
                "status": "Active",
                "opened_at": "2026-08-10T10:30:00+02:00",
            },
            # `007` and `7` are two different accounts, and nothing may treat them as one.
            {"account_id": "007", "roles": ["OPS_CLERK"], "status": "Active", "opened_at": "2026-08-11T00:00:00Z"},
            {"account_id": "7", "roles": ["OPS_CLERK"], "status": "Disabled", "opened_at": "2026-08-12T00:00:00Z"},
        ],
    },
    separators=(",", ":"),
)

SNAPSHOTS = [
    {
        "name": "accessgate-accounts",
        "substrate": "json",
        "evidenceId": EVIDENCE,
        "text": ACCOUNTS,
    },
    {
        "name": "role-matrix",
        "substrate": "sheet",
        "evidenceId": EVIDENCE,
        "text": ROLE_MATRIX.read_text(encoding="utf-8"),
        "source": "fixtures/northstar/generated/role-matrix.csv",
    },
]

BY_NAME = {snapshot["name"]: snapshot for snapshot in SNAPSHOTS}

CELLS = [
    ("json value and its property key", "accessgate-accounts", "$.accounts[0].account_id"),
    ("json array value", "accessgate-accounts", "$.accounts[0].roles"),
    ("json offset time", "accessgate-accounts", "$.accounts[0].opened_at"),
    ("json leading-zero identifier", "accessgate-accounts", "$.accounts[1].account_id"),
    ("json identifier without the zeros", "accessgate-accounts", "$.accounts[2].account_id"),
    ("json index past the end", "accessgate-accounts", "$.accounts[3].account_id"),
    ("json field the row does not carry", "accessgate-accounts", "$.accounts[0].closed_at"),
    ("json collection the envelope does not carry", "accessgate-accounts", "$.employees[0].account_id"),
    ("json envelope key that is not a row list", "accessgate-accounts", "$.schema[0].account_id"),
    # The real RoleMatrix, including the `entry` ordinal that keeps AMBIGUOUS_DUAL's two
    # conflicting policy entries apart. Rows 16 and 18 are the same role, different entry.
    ("sheet header cell", "role-matrix", "$.rows[0].role"),
    ("sheet ordinal is a string", "role-matrix", "$.rows[0].entry"),
    ("sheet first ambiguous entry", "role-matrix", "$.rows[16].entry"),
    ("sheet second ambiguous entry", "role-matrix", "$.rows[18].entry"),
    ("sheet permission column", "role-matrix", "$.rows[18].permission"),
    ("sheet last data row", "role-matrix", "$.rows[35].role"),
    ("sheet index past the last data row", "role-matrix", "$.rows[36].role"),
    ("sheet collection that is not rows", "role-matrix", "$.sheet[0].role"),
    ("sheet column the header does not declare", "role-matrix", "$.rows[0].scope"),
    ("locator with a leading-zero index", "role-matrix", "$.rows[00].role"),
    ("locator that is not the grammar", "role-matrix", "rows[0].role"),
]


def attribute(name, original, normalized, locator, label, text):
    return {
        "name": name,
        "originalValue": original,
        "normalizedValue": normalized,
        "grounding": {
            "evidenceId": EVIDENCE,
            "locator": locator,
            "label": label,
            "extractedText": text,
        },
        "corroboration": None,
    }


ATTRIBUTES = [
    (
        "a faithful capture of a json string",
        "accessgate-accounts",
        attribute("account_id", "AG-1001", "AG-1001", "$.accounts[0].account_id", "account_id", "AG-1001"),
    ),
    (
        "a faithful capture of a json array",
        "accessgate-accounts",
        attribute("roles", ["AP_CLERK"], ["AP_CLERK"], "$.accounts[0].roles", "roles", '["AP_CLERK"]'),
    ),
    (
        "an offset time normalized to UTC with the original retained",
        "accessgate-accounts",
        attribute(
            "opened_at",
            "2026-08-10T10:30:00+02:00",
            "2026-08-10T08:30:00.000Z",
            "$.accounts[0].opened_at",
            "opened_at",
            "2026-08-10T10:30:00+02:00",
        ),
    ),
    (
        "an offset time silently shifted instead of normalized",
        "accessgate-accounts",
        attribute(
            "opened_at",
            "2026-08-10T10:30:00+02:00",
            "2026-08-10T10:30:00.000Z",
            "$.accounts[0].opened_at",
            "opened_at",
            "2026-08-10T10:30:00+02:00",
        ),
    ),
    (
        "a value the snapshot does not hold",
        "accessgate-accounts",
        attribute("status", "Active", "Active", "$.accounts[2].status", "status", "Active"),
    ),
    (
        "a label the snapshot does not use",
        "accessgate-accounts",
        attribute("status", "Active", "Active", "$.accounts[0].status", "Status", "Active"),
    ),
    (
        "a leading-zero identifier kept as it was served",
        "accessgate-accounts",
        attribute("account_id", "007", "007", "$.accounts[1].account_id", "account_id", "007"),
    ),
    (
        "a leading-zero identifier normalized to its numeric spelling",
        "accessgate-accounts",
        attribute("account_id", "007", "7", "$.accounts[1].account_id", "account_id", "007"),
    ),
    (
        "007 recorded against the row that holds 7",
        "accessgate-accounts",
        attribute("account_id", "007", "007", "$.accounts[2].account_id", "account_id", "007"),
    ),
    (
        "extracted text that is not the text at the locator",
        "accessgate-accounts",
        attribute("account_id", "AG-1001", "AG-1001", "$.accounts[0].account_id", "account_id", "AG-1002"),
    ),
    (
        "a locator that resolves to nothing",
        "accessgate-accounts",
        attribute("account_id", "AG-1001", "AG-1001", "$.accounts[9].account_id", "account_id", "AG-1001"),
    ),
    (
        "a sheet cell read through its header",
        "role-matrix",
        attribute("role", "AP_CLERK", "AP_CLERK", "$.rows[0].role", "role", "AP_CLERK"),
    ),
    (
        "a sheet ordinal that keeps two policy entries apart",
        "role-matrix",
        attribute("entry", "11", "11", "$.rows[18].entry", "entry", "11"),
    ),
    (
        "a sheet ordinal recorded from the wrong entry",
        "role-matrix",
        attribute("entry", "10", "10", "$.rows[18].entry", "entry", "10"),
    ),
]


def main() -> int:
    cells = []
    for name, snapshot, locator in CELLS:
        found = cell(BY_NAME[snapshot], locator)
        cells.append(
            {
                "name": name,
                "snapshot": snapshot,
                "locator": locator,
                "resolves": found is not None,
                "value": None if found is None else found["value"],
                "label": None if found is None else found["label"],
            }
        )
    attributes = []
    for name, snapshot, value in ATTRIBUTES:
        corroboration, failure = judge(BY_NAME[snapshot], value)
        attributes.append(
            {
                "name": name,
                "snapshot": snapshot,
                "attribute": value,
                "corroboration": corroboration,
                "failure": failure,
            }
        )
    OUT.write_text(
        json.dumps(
            {
                "producer": f"Python {sys.version.split()[0]} + rfc8785 {rfc8785.__version__ if hasattr(rfc8785, '__version__') else '0.1.4'} + csv + json",
                "producedBy": "scripts/make-snapshot-extraction-golden.py",
                "regenerateWith": "uv run scripts/make-snapshot-extraction-golden.py",
                "why": (
                    "Structural Snapshot extraction vectors, produced by an implementation that is NOT "
                    "the code under test. packages/domain/src/runs/structural-snapshot.ts is checked "
                    "against these cells and verdicts; a fixture produced by that module would prove "
                    "only that it equals itself, which is no evidence at all for an extractor whose "
                    "whole job is to be a second opinion on what an adapter asserted."
                ),
                "grammar": (
                    "A locator is $.<collection>[<index>].<field>, anchored, with no '.', '[' or ']' "
                    "inside either name and no leading zero on the index. For a sheet the collection "
                    "segment is exactly 'rows', the index is the 0-based DATA row after the header and "
                    "after a leading '# SYNTHETIC' marker line, and the label is the header cell. For "
                    "json the collection is an envelope key holding a list of objects, the index is the "
                    "0-based position in it, and the label is the property key."
                ),
                "matching": (
                    "An attribute is matched only when the locator resolves, the re-read label equals "
                    "the declared label, the re-read value equals originalValue as RFC 8785 canonical "
                    "bytes, the grounding's extractedText is the text of that value, and normalizedValue "
                    "is either that value or its UTC normalization. Anything else is contradictory, and "
                    "nothing is ever repaired by preferring one side."
                ),
                "snapshots": SNAPSHOTS,
                "cells": cells,
                "attributes": attributes,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(cells)} cells, {len(attributes)} attributes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
