# /// script
# requires-python = ">=3.11"
# dependencies = ["rfc8785==0.1.4"]
# ///
"""Produce tests/fixtures/binding-digest-golden.json.

The point of this script is that it is NOT TypeScript. `packages/domain/src/sources/
population-source.ts` computes the Population Source binding digest, and a fixture
generated by that code would only prove the code equals itself. Everything here — the
five-key envelope, the RFC 8785 canonical bytes, and the SHA-256 — is produced by an
independent implementation: `rfc8785` from PyPI and the standard library's `hashlib`.

The envelopes below are written out BY HAND rather than derived from the inputs by a
Python copy of the projection rule. That is deliberate: the projection (which key holds
what, which member is a list and which is a set) is exactly the part a shared helper
would stop checking. A reviewer can read each `envelope` and see the five keys.

The two normalization rules are opposite on purpose and each has a vector that fails if
they are swapped:

  * `declared_schema` is an ORDERED list — a schema declares field positions, and
    `[account, amount]` is not the same declaration as `[amount, account]`. Duplicates
    are removed and blanks dropped, but the typed order is hashed.
  * `sensitive_fields` is a SET — sorted by UTF-16 code unit — because masking asks only
    whether a field is in the group.

Run it from the repository root:

    uv run scripts/make-binding-digest-golden.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

import rfc8785

OUT = pathlib.Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "binding-digest-golden.json"

# (name, note, digest input as the domain module receives it, hand-written envelope)
VECTORS: list[tuple[str, str, dict, dict]] = [
    (
        "versioned-file-cover-sheet",
        "A versioned file whose expected count comes from a signed cover sheet. The "
        "declared schema keeps the order it was typed in — it is a positional "
        "declaration — while the sensitive fields are sorted, because masking is a "
        "membership question. Both lists are given here with a duplicate and a blank, "
        "and both drop them.",
        {
            "kind": "versioned-file",
            "location": "  s3://synthetic-bucket/hr/leavers/2026-08.csv  ",
            "declaredSchema": [
                "employee_id",
                "employment_status",
                "termination_date",
                "salary",
                "employee_id",
                "   ",
            ],
            "declaredCountMechanism": "cover-sheet",
            "sensitiveFields": ["salary", "employee_id", "salary"],
        },
        {
            "declared_count_mechanism": "cover-sheet",
            # Typed order, deduplicated. NOT sorted: sorting it would give
            # ["employee_id", "employment_status", "salary", "termination_date"].
            "declared_schema": [
                "employee_id",
                "employment_status",
                "termination_date",
                "salary",
            ],
            "kind": "versioned-file",
            "location": "s3://synthetic-bucket/hr/leavers/2026-08.csv",
            # Sorted. NOT the typed order, which was ["salary", "employee_id"].
            "sensitive_fields": ["employee_id", "salary"],
        },
    ),
    (
        "read-only-api-count-endpoint",
        "A read-only API whose expected count comes from a count endpoint, with no "
        "sensitive field designated. Every key is still present: an absent value is an "
        "empty list, never a missing key.",
        {
            "kind": "read-only-api",
            "location": "https://accessgate.synthetic.invalid/api/accounts",
            "declaredSchema": ["account_id", "owner", "status"],
            "declaredCountMechanism": "count-endpoint",
            "sensitiveFields": [],
        },
        {
            "declared_count_mechanism": "count-endpoint",
            "declared_schema": ["account_id", "owner", "status"],
            "kind": "read-only-api",
            "location": "https://accessgate.synthetic.invalid/api/accounts",
            "sensitive_fields": [],
        },
    ),
    (
        "manual-upload-no-location",
        "A manual upload names nowhere: the file arrives with the Run. The location "
        "slot is null rather than absent, so this kind produces the same five keys as "
        "every other. A location typed anyway is dropped, which is why one is given "
        "here.",
        {
            "kind": "manual-upload",
            "location": "https://ignored.synthetic.invalid/never-read",
            "declaredSchema": ["voucher_no", "amount"],
            "declaredCountMechanism": "none",
            "sensitiveFields": ["amount"],
        },
        {
            "declared_count_mechanism": "none",
            "declared_schema": ["voucher_no", "amount"],
            "kind": "manual-upload",
            "location": None,
            "sensitive_fields": ["amount"],
        },
    ),
    (
        "schema-order-reversed",
        "Byte-identical to the first vector except that two schema fields are swapped. "
        "Its digest must differ: the declared schema is ordered, and a parser told the "
        "other order would read the wrong column.",
        {
            "kind": "versioned-file",
            "location": "s3://synthetic-bucket/hr/leavers/2026-08.csv",
            "declaredSchema": [
                "employee_id",
                "employment_status",
                "salary",
                "termination_date",
            ],
            "declaredCountMechanism": "cover-sheet",
            "sensitiveFields": ["employee_id", "salary"],
        },
        {
            "declared_count_mechanism": "cover-sheet",
            "declared_schema": [
                "employee_id",
                "employment_status",
                "salary",
                "termination_date",
            ],
            "kind": "versioned-file",
            "location": "s3://synthetic-bucket/hr/leavers/2026-08.csv",
            "sensitive_fields": ["employee_id", "salary"],
        },
    ),
    (
        "sensitive-fields-order-irrelevant",
        "Byte-identical to the first vector except that the sensitive fields are typed "
        "in the other order. Its digest must EQUAL the first vector's: they are a set. "
        "This is the vector that fails if sensitive_fields is ever hashed as a list.",
        {
            "kind": "versioned-file",
            "location": "s3://synthetic-bucket/hr/leavers/2026-08.csv",
            "declaredSchema": [
                "employee_id",
                "employment_status",
                "termination_date",
                "salary",
            ],
            "declaredCountMechanism": "cover-sheet",
            "sensitiveFields": ["salary", "employee_id"],
        },
        {
            "declared_count_mechanism": "cover-sheet",
            "declared_schema": [
                "employee_id",
                "employment_status",
                "termination_date",
                "salary",
            ],
            "kind": "versioned-file",
            "location": "s3://synthetic-bucket/hr/leavers/2026-08.csv",
            "sensitive_fields": ["employee_id", "salary"],
        },
    ),
    (
        "unicode-field-names",
        "Multi-byte UTF-8 field names and location. RFC 8785 sorts object keys by "
        "UTF-16 code unit and emits the characters unescaped, and the domain module "
        "sorts the sensitive-field set the same way. The U+FFFD sentinel is what makes "
        "that testable: it sorts AFTER the astral-plane emoji by UTF-16 code unit "
        "(0xD83D, the emoji's leading surrogate, is below 0xFFFD) and BEFORE it by code "
        "point (U+FFFD < U+1F50E), so a code-point comparator fails this vector.",
        {
            "kind": "versioned-file",
            "location": "s3://synthetic-bucket/ledgers/2026/Qé.csv",
            "declaredSchema": ["N° de pièce", "金額", "🔎 locator", "\ufffd sentinel"],
            "declaredCountMechanism": "cover-sheet",
            "sensitiveFields": ["\ufffd sentinel", "🔎 locator", "金額"],
        },
        {
            "declared_count_mechanism": "cover-sheet",
            # Typed order, untouched.
            "declared_schema": ["N° de pièce", "金額", "🔎 locator", "\ufffd sentinel"],
            "kind": "versioned-file",
            "location": "s3://synthetic-bucket/ledgers/2026/Qé.csv",
            # UTF-16 code-unit order.
            "sensitive_fields": ["金額", "🔎 locator", "\ufffd sentinel"],
        },
    ),
]

FIVE_KEYS = {
    "declared_count_mechanism",
    "declared_schema",
    "kind",
    "location",
    "sensitive_fields",
}


def main() -> int:
    vectors = []
    for name, note, digest_input, envelope in VECTORS:
        if set(envelope) != FIVE_KEYS:
            raise SystemExit(f"{name}: envelope must hold exactly the five binding keys")
        for field in envelope["sensitive_fields"]:
            if field not in envelope["declared_schema"]:
                raise SystemExit(f"{name}: a sensitive field must be in the declared schema")
        canonical = rfc8785.dumps(envelope)
        vectors.append(
            {
                "name": name,
                "note": note,
                "input": digest_input,
                "envelope": envelope,
                "canonicalText": canonical.decode("utf-8"),
                "digest": hashlib.sha256(canonical).hexdigest(),
            }
        )

    # Two vectors deliberately SHARE a digest — the set-vs-list pair — so the check is
    # that every DISTINCT envelope has a distinct digest, and that the pair that must
    # agree does.
    by_envelope: dict[str, str] = {}
    for vector in vectors:
        key = json.dumps(vector["envelope"], sort_keys=True, ensure_ascii=False)
        seen = by_envelope.setdefault(key, vector["digest"])
        if seen != vector["digest"]:
            raise SystemExit("one envelope produced two digests")
    if len({v["digest"] for v in vectors}) != len(by_envelope):
        raise SystemExit("two different envelopes share a digest; the fixture would prove nothing")

    fixture = {
        "producer": f"Python {sys.version.split()[0]} + rfc8785 0.1.4 + hashlib.sha256",
        "producedBy": "scripts/make-binding-digest-golden.py",
        "regenerateWith": "uv run scripts/make-binding-digest-golden.py",
        "why": (
            "Population Source binding digest vectors, produced by an implementation "
            "that is NOT the code under test. packages/domain/src/sources/"
            "population-source.ts is checked against these bytes; a fixture produced by "
            "that module would prove only that it equals itself. The envelopes in the "
            "generator are written out by hand, so the projection from a binding to its "
            "five hashed keys is checked too, not just the hash of an envelope this "
            "repository derived."
        ),
        "algorithm": (
            "digest = SHA-256( RFC 8785 canonical JSON of the five-key envelope "
            "{declared_count_mechanism, declared_schema, kind, location, "
            "sensitive_fields} ), lower-case hex. declared_schema keeps its typed "
            "order; sensitive_fields is sorted by UTF-16 code unit."
        ),
        "vectors": vectors,
    }
    OUT.write_text(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(vectors)} vectors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
