import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  corroborateAttribute,
  parseSnapshotLocator,
  readSnapshotCell,
  readStructuralSnapshot,
  utf8Bytes,
  type ObservationAttribute,
  type ParsedSnapshot,
  type SnapshotSubstrate,
} from '@intellifin/domain';

/**
 * The Structural Snapshot extractor against vectors this repository's TypeScript did not
 * produce.
 *
 * `scripts/make-snapshot-extraction-golden.py` writes them with Python's own `csv`,
 * `json`, `datetime` and PyPI `rfc8785`. That is the whole point: the extractor exists to
 * be a SECOND OPINION on what an adapter asserted, and a vector generated by the extractor
 * would prove only that it agrees with itself — which is exactly the property an
 * Observation already has without it.
 *
 * The `sheet` snapshot is the real `fixtures/northstar/generated/role-matrix.csv`, and the
 * test reads that file off disk and requires the fixture to hold the same bytes: a
 * regenerated dataset that changes the served CSV must fail here rather than quietly leave
 * the vectors describing a file nobody serves any more.
 */

interface GoldenSnapshot {
  readonly name: string;
  readonly substrate: SnapshotSubstrate;
  readonly evidenceId: string;
  readonly text: string;
  readonly source?: string;
}

interface GoldenCell {
  readonly name: string;
  readonly snapshot: string;
  readonly locator: string;
  readonly resolves: boolean;
  readonly value: unknown;
  readonly label: string | null;
}

interface GoldenAttribute {
  readonly name: string;
  readonly snapshot: string;
  readonly attribute: ObservationAttribute;
  readonly corroboration: string | null;
  readonly failure: string | null;
}

interface Golden {
  readonly producer: string;
  readonly producedBy: string;
  readonly snapshots: readonly GoldenSnapshot[];
  readonly cells: readonly GoldenCell[];
  readonly attributes: readonly GoldenAttribute[];
}

const golden = JSON.parse(
  readFileSync(
    fileURLToPath(new URL('../fixtures/snapshot-extraction-golden.json', import.meta.url)),
    'utf8',
  ),
) as Golden;

const parsed = new Map<string, ParsedSnapshot>(
  golden.snapshots.map((snapshot) => [
    snapshot.name,
    readStructuralSnapshot({
      evidenceId: snapshot.evidenceId,
      substrate: snapshot.substrate,
      bytes: utf8Bytes(snapshot.text),
    }),
  ]),
);

/** One snapshot, addressed by the Evidence id every golden grounding names. */
function only(name: string): ReadonlyMap<string, ParsedSnapshot> {
  const snapshot = golden.snapshots.find((entry) => entry.name === name)!;
  return new Map([[snapshot.evidenceId, parsed.get(name)!]]);
}

describe('the golden vectors themselves', () => {
  it('were produced by something that is not this codebase', () => {
    // A fixture regenerated from the extractor would prove only that it equals itself.
    expect(golden.producer.startsWith('Python')).toBe(true);
    expect(golden.producedBy).toBe('scripts/make-snapshot-extraction-golden.py');
    expect(golden.cells.length).toBeGreaterThan(10);
    expect(golden.attributes.length).toBeGreaterThan(10);
  });

  it('carries the RoleMatrix bytes the synthetic system really serves', () => {
    const sheet = golden.snapshots.find((entry) => entry.source !== undefined)!;
    const served = readFileSync(
      fileURLToPath(new URL(`../../${sheet.source!}`, import.meta.url)),
      'utf8',
    );
    expect(sheet.text).toBe(served);
    // The leading `entry` ordinal Story 3.3 added, still there: without it two conflicting
    // policy entries for one role flatten into one permission set.
    expect(served.split('\n')[1]).toBe('entry,role,permission');
  });

  it('reads every snapshot it declares', () => {
    for (const [name, view] of parsed) expect([name, view.ok]).toEqual([name, true]);
  });
});

describe('the locator grammar and the label rule', () => {
  for (const cell of golden.cells) {
    it(cell.name, () => {
      const locator = parseSnapshotLocator(cell.locator);
      const found = locator === null ? null : readSnapshotCell(parsed.get(cell.snapshot)!, locator);
      expect(found !== null).toBe(cell.resolves);
      if (found === null) return;
      expect(found.value).toEqual(cell.value);
      expect(found.label).toBe(cell.label);
    });
  }
});

describe('the per-attribute verdict', () => {
  for (const entry of golden.attributes) {
    it(entry.name, () => {
      const judged = corroborateAttribute(entry.attribute, only(entry.snapshot));
      expect(judged.corroboration).toBe(entry.corroboration);
      expect(judged.failure).toBe(entry.failure);
      expect(judged.name).toBe(entry.attribute.name);
    });
  }

  it('agrees with Python on which vectors are matched and which are not', () => {
    // A guard on the vectors, not on the code: a generator that produced only matches, or
    // only failures, would make every case above pass for the wrong reason.
    const matched = golden.attributes.filter((entry) => entry.corroboration === 'matched');
    expect(matched.length).toBeGreaterThan(2);
    expect(golden.attributes.length - matched.length).toBeGreaterThan(4);
    expect(new Set(golden.attributes.map((entry) => entry.failure))).toContain(
      'normalization-unauthorized',
    );
  });
});
